// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wa_in_i2910_dout,
        wa_in_i2910_num_data_valid,
        wa_in_i2910_fifo_cap,
        wa_in_i2910_empty_n,
        wa_in_i2910_read,
        convInp_i31_din,
        convInp_i31_num_data_valid,
        convInp_i31_fifo_cap,
        convInp_i31_full_n,
        convInp_i31_write,
        bound
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] wa_in_i2910_dout;
input  [2:0] wa_in_i2910_num_data_valid;
input  [2:0] wa_in_i2910_fifo_cap;
input   wa_in_i2910_empty_n;
output   wa_in_i2910_read;
output  [31:0] convInp_i31_din;
input  [2:0] convInp_i31_num_data_valid;
input  [2:0] convInp_i31_fifo_cap;
input   convInp_i31_full_n;
output   convInp_i31_write;
input  [39:0] bound;

reg ap_idle;
reg wa_in_i2910_read;
reg convInp_i31_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln107_reg_842;
reg   [0:0] and_ln153_reg_881;
reg    ap_predicate_op149_read_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg   [0:0] icmp_ln107_reg_842_pp0_iter3_reg;
reg   [0:0] icmp_ln123_reg_846;
reg   [0:0] icmp_ln123_reg_846_pp0_iter3_reg;
reg    ap_predicate_op177_write_state5;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln104_fu_375_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    wa_in_i2910_blk_n;
wire    ap_block_pp0_stage0;
reg    convInp_i31_blk_n;
reg   [31:0] reg_315;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln104_reg_829;
wire   [0:0] icmp_ln107_fu_448_p2;
wire   [0:0] and_ln153_fu_599_p2;
wire   [0:0] icmp_ln105_fu_386_p2;
reg   [0:0] icmp_ln105_reg_833;
wire   [1:0] trunc_ln98_fu_444_p1;
reg   [1:0] trunc_ln98_reg_838;
wire   [0:0] icmp_ln123_fu_454_p2;
wire   [1:0] add_ln124_3_fu_479_p2;
reg   [1:0] add_ln124_3_reg_850;
wire   [31:0] p_0_fu_701_p11;
reg   [31:0] p_0_reg_891;
reg    ap_condition_exit_pp0_iter2_stage0;
reg   [4:0] inputBuf_address0;
reg    inputBuf_ce0;
reg    inputBuf_we0;
wire   [4:0] inputBuf_address1;
reg    inputBuf_ce1;
wire   [31:0] inputBuf_q1;
reg   [4:0] inputBuf_1_address0;
reg    inputBuf_1_ce0;
reg    inputBuf_1_we0;
wire   [4:0] inputBuf_1_address1;
reg    inputBuf_1_ce1;
wire   [31:0] inputBuf_1_q1;
reg   [4:0] inputBuf_2_address0;
reg    inputBuf_2_ce0;
reg    inputBuf_2_we0;
wire   [4:0] inputBuf_2_address1;
reg    inputBuf_2_ce1;
wire   [31:0] inputBuf_2_q1;
reg   [4:0] inputBuf_3_address0;
reg    inputBuf_3_ce0;
reg    inputBuf_3_we0;
wire   [4:0] inputBuf_3_address1;
reg    inputBuf_3_ce1;
wire   [31:0] inputBuf_3_q1;
wire   [63:0] zext_ln129_fu_503_p1;
wire   [63:0] zext_ln156_fu_724_p1;
wire   [63:0] zext_ln110_fu_732_p1;
reg   [31:0] read_block_fu_74;
wire   [31:0] select_ln98_fu_432_p3;
wire   [31:0] grp_fu_291_p2;
wire   [0:0] grp_fu_285_p2;
wire    ap_loop_init;
reg   [7:0] i_09_fu_78;
wire   [7:0] i_fu_398_p3;
reg   [39:0] indvar_flatten_fu_82;
wire   [39:0] add_ln104_fu_380_p2;
reg   [31:0] k_y_fu_86;
wire   [31:0] k_y_4_fu_564_p3;
wire   [0:0] icmp_ln132_fu_517_p2;
wire   [0:0] icmp_ln135_fu_534_p2;
reg   [31:0] k_x_fu_90;
wire   [31:0] k_x_3_fu_528_p2;
reg   [31:0] current_block_write_11_fu_94;
wire   [31:0] grp_fu_307_p3;
reg   [31:0] inp_fu_98;
wire   [31:0] inp_9_fu_556_p3;
wire   [31:0] inp_8_fu_660_p2;
reg   [31:0] count_simd_fu_102;
wire   [31:0] count_simd_3_fu_511_p2;
reg   [31:0] current_line_fu_106;
wire   [31:0] grp_fu_279_p2;
reg   [31:0] counter_internal_block_fu_110;
wire   [31:0] counter_internal_block_9_fu_647_p3;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_296_p2;
wire   [0:0] grp_fu_301_p2;
wire   [7:0] add_ln105_fu_392_p2;
wire   [31:0] k_y_3_fu_469_p2;
wire   [1:0] trunc_ln124_fu_475_p1;
wire   [1:0] trunc_ln128_fu_485_p1;
wire   [4:0] shl_ln_fu_489_p3;
wire   [4:0] trunc_ln105_fu_440_p1;
wire   [4:0] current_line_in_block_fu_497_p2;
wire   [0:0] icmp_ln138_fu_550_p2;
wire   [0:0] icmp_ln153_fu_587_p2;
wire   [0:0] icmp_ln153_3_fu_593_p2;
wire   [31:0] counter_internal_block_8_fu_635_p2;
wire   [0:0] icmp_ln172_fu_641_p2;
wire   [31:0] p_0_fu_701_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op74_load_state3;
reg    ap_enable_operation_74;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op144_load_state4;
reg    ap_enable_operation_144;
reg    ap_enable_state4_pp0_iter3_stage0;
reg    ap_predicate_op159_store_state4;
reg    ap_enable_operation_159;
reg    ap_predicate_op173_store_state4;
reg    ap_enable_operation_173;
reg    ap_predicate_op75_load_state3;
reg    ap_enable_operation_75;
reg    ap_predicate_op145_load_state4;
reg    ap_enable_operation_145;
reg    ap_predicate_op157_store_state4;
reg    ap_enable_operation_157;
reg    ap_predicate_op171_store_state4;
reg    ap_enable_operation_171;
reg    ap_predicate_op76_load_state3;
reg    ap_enable_operation_76;
reg    ap_predicate_op146_load_state4;
reg    ap_enable_operation_146;
reg    ap_predicate_op155_store_state4;
reg    ap_enable_operation_155;
reg    ap_predicate_op169_store_state4;
reg    ap_enable_operation_169;
reg    ap_predicate_op77_load_state3;
reg    ap_enable_operation_77;
reg    ap_predicate_op147_load_state4;
reg    ap_enable_operation_147;
reg    ap_predicate_op161_store_state4;
reg    ap_enable_operation_161;
reg    ap_predicate_op175_store_state4;
reg    ap_enable_operation_175;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_667;
reg    ap_condition_671;
reg    ap_condition_674;
reg    ap_condition_677;
reg    ap_condition_680;
reg    ap_condition_683;
wire   [1:0] p_0_fu_701_p1;
wire   [1:0] p_0_fu_701_p3;
wire  signed [1:0] p_0_fu_701_p5;
wire  signed [1:0] p_0_fu_701_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 read_block_fu_74 = 32'd0;
#0 i_09_fu_78 = 8'd0;
#0 indvar_flatten_fu_82 = 40'd0;
#0 k_y_fu_86 = 32'd0;
#0 k_x_fu_90 = 32'd0;
#0 current_block_write_11_fu_94 = 32'd0;
#0 inp_fu_98 = 32'd0;
#0 count_simd_fu_102 = 32'd0;
#0 current_line_fu_106 = 32'd0;
#0 counter_internal_block_fu_110 = 32'd0;
#0 ap_done_reg = 1'b0;
end

BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_3_inputBvdy #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_address0),
    .ce0(inputBuf_ce0),
    .we0(inputBuf_we0),
    .d0(wa_in_i2910_dout),
    .address1(inputBuf_address1),
    .ce1(inputBuf_ce1),
    .q1(inputBuf_q1)
);

BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_3_inputBvdy #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_address0),
    .ce0(inputBuf_1_ce0),
    .we0(inputBuf_1_we0),
    .d0(wa_in_i2910_dout),
    .address1(inputBuf_1_address1),
    .ce1(inputBuf_1_ce1),
    .q1(inputBuf_1_q1)
);

BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_3_inputBvdy #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_address0),
    .ce0(inputBuf_2_ce0),
    .we0(inputBuf_2_we0),
    .d0(wa_in_i2910_dout),
    .address1(inputBuf_2_address1),
    .ce1(inputBuf_2_ce1),
    .q1(inputBuf_2_q1)
);

BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_3_inputBvdy #(
    .DataWidth( 32 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
inputBuf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_address0),
    .ce0(inputBuf_3_ce0),
    .we0(inputBuf_3_we0),
    .d0(wa_in_i2910_dout),
    .address1(inputBuf_3_address1),
    .ce1(inputBuf_3_ce1),
    .q1(inputBuf_3_q1)
);

BlackBoxJam_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U559(
    .din0(inputBuf_q1),
    .din1(inputBuf_1_q1),
    .din2(inputBuf_2_q1),
    .din3(inputBuf_3_q1),
    .def(p_0_fu_701_p9),
    .sel(add_ln124_3_reg_850),
    .dout(p_0_fu_701_p11)
);

BlackBoxJam_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln132_fu_517_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        count_simd_fu_102 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln132_fu_517_p2 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0))) begin
        count_simd_fu_102 <= count_simd_3_fu_511_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        counter_internal_block_fu_110 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0))) begin
        counter_internal_block_fu_110 <= counter_internal_block_9_fu_647_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_11_fu_94 <= 32'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        current_block_write_11_fu_94 <= grp_fu_307_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        current_line_fu_106 <= 32'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd0) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd0) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        current_line_fu_106 <= grp_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_09_fu_78 <= 8'd0;
        end else if (((icmp_ln104_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_09_fu_78 <= i_fu_398_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 40'd0;
        end else if (((icmp_ln104_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln104_fu_380_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            inp_fu_98 <= 32'd0;
        end else if ((1'b1 == ap_condition_671)) begin
            inp_fu_98 <= inp_8_fu_660_p2;
        end else if ((1'b1 == ap_condition_667)) begin
            inp_fu_98 <= inp_9_fu_556_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_534_p2 == 1'd1) & (icmp_ln132_fu_517_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        k_x_fu_90 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_534_p2 == 1'd0) & (icmp_ln132_fu_517_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0))) begin
        k_x_fu_90 <= k_x_3_fu_528_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_y_fu_86 <= 32'd0;
        end else if ((1'b1 == ap_condition_667)) begin
            k_y_fu_86 <= k_y_4_fu_564_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_fu_74 <= 32'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        read_block_fu_74 <= grp_fu_291_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd0) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (grp_fu_285_p2 == 1'd0) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        read_block_fu_74 <= select_ln98_fu_432_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln124_3_reg_850 <= add_ln124_3_fu_479_p2;
        and_ln153_reg_881 <= and_ln153_fu_599_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln107_reg_842 <= icmp_ln107_fu_448_p2;
        icmp_ln107_reg_842_pp0_iter3_reg <= icmp_ln107_reg_842;
        icmp_ln123_reg_846 <= icmp_ln123_fu_454_p2;
        icmp_ln123_reg_846_pp0_iter3_reg <= icmp_ln123_reg_846;
        p_0_reg_891 <= p_0_fu_701_p11;
        trunc_ln98_reg_838 <= trunc_ln98_fu_444_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln104_reg_829 <= icmp_ln104_fu_375_p2;
        icmp_ln105_reg_833 <= icmp_ln105_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_fu_599_p2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0)))) begin
        reg_315 <= current_line_fu_106;
    end
end

always @ (*) begin
    if (((icmp_ln104_fu_375_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln104_reg_829 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op177_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        convInp_i31_blk_n = convInp_i31_full_n;
    end else begin
        convInp_i31_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op177_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        convInp_i31_write = 1'b1;
    end else begin
        convInp_i31_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_674)) begin
        if ((icmp_ln107_reg_842 == 1'd1)) begin
            inputBuf_1_address0 = zext_ln110_fu_732_p1;
        end else if (((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0))) begin
            inputBuf_1_address0 = zext_ln156_fu_724_p1;
        end else begin
            inputBuf_1_address0 = 'bx;
        end
    end else begin
        inputBuf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd1)))) begin
        inputBuf_1_ce0 = 1'b1;
    end else begin
        inputBuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inputBuf_1_ce1 = 1'b1;
    end else begin
        inputBuf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd1)))) begin
        inputBuf_1_we0 = 1'b1;
    end else begin
        inputBuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_677)) begin
        if ((icmp_ln107_reg_842 == 1'd1)) begin
            inputBuf_2_address0 = zext_ln110_fu_732_p1;
        end else if (((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0))) begin
            inputBuf_2_address0 = zext_ln156_fu_724_p1;
        end else begin
            inputBuf_2_address0 = 'bx;
        end
    end else begin
        inputBuf_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd2)))) begin
        inputBuf_2_ce0 = 1'b1;
    end else begin
        inputBuf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inputBuf_2_ce1 = 1'b1;
    end else begin
        inputBuf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd2)))) begin
        inputBuf_2_we0 = 1'b1;
    end else begin
        inputBuf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_680)) begin
        if ((icmp_ln107_reg_842 == 1'd1)) begin
            inputBuf_3_address0 = zext_ln110_fu_732_p1;
        end else if (((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0))) begin
            inputBuf_3_address0 = zext_ln156_fu_724_p1;
        end else begin
            inputBuf_3_address0 = 'bx;
        end
    end else begin
        inputBuf_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd3)))) begin
        inputBuf_3_ce0 = 1'b1;
    end else begin
        inputBuf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inputBuf_3_ce1 = 1'b1;
    end else begin
        inputBuf_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd3)))) begin
        inputBuf_3_we0 = 1'b1;
    end else begin
        inputBuf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_683)) begin
        if ((icmp_ln107_reg_842 == 1'd1)) begin
            inputBuf_address0 = zext_ln110_fu_732_p1;
        end else if (((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0))) begin
            inputBuf_address0 = zext_ln156_fu_724_p1;
        end else begin
            inputBuf_address0 = 'bx;
        end
    end else begin
        inputBuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd0)))) begin
        inputBuf_ce0 = 1'b1;
    end else begin
        inputBuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        inputBuf_ce1 = 1'b1;
    end else begin
        inputBuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd0)))) begin
        inputBuf_we0 = 1'b1;
    end else begin
        inputBuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op149_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        wa_in_i2910_blk_n = wa_in_i2910_empty_n;
    end else begin
        wa_in_i2910_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_reg_842 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op149_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        wa_in_i2910_read = 1'b1;
    end else begin
        wa_in_i2910_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln104_fu_380_p2 = (indvar_flatten_fu_82 + 40'd1);

assign add_ln105_fu_392_p2 = (i_09_fu_78 + 8'd1);

assign add_ln124_3_fu_479_p2 = (trunc_ln124_fu_475_p1 + trunc_ln98_fu_444_p1);

assign and_ln153_fu_599_p2 = (icmp_ln153_fu_587_p2 & icmp_ln153_3_fu_593_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (((icmp_ln107_reg_842 == 1'd1) & (wa_in_i2910_empty_n == 1'b0)) | ((ap_predicate_op149_read_state4 == 1'b1) & (wa_in_i2910_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((ap_predicate_op177_write_state5 == 1'b1) & (convInp_i31_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_667 = ((icmp_ln135_fu_534_p2 == 1'd1) & (icmp_ln132_fu_517_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0));
end

always @ (*) begin
    ap_condition_671 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln107_fu_448_p2 == 1'd1) & (icmp_ln104_reg_829 == 1'd0));
end

always @ (*) begin
    ap_condition_674 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd1));
end

always @ (*) begin
    ap_condition_677 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd2));
end

always @ (*) begin
    ap_condition_680 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd3));
end

always @ (*) begin
    ap_condition_683 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln98_reg_838 == 2'd0));
end

always @ (*) begin
    ap_enable_operation_144 = (ap_predicate_op144_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_145 = (ap_predicate_op145_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_146 = (ap_predicate_op146_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_147 = (ap_predicate_op147_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_155 = (ap_predicate_op155_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_157 = (ap_predicate_op157_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_159 = (ap_predicate_op159_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_161 = (ap_predicate_op161_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_169 = (ap_predicate_op169_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_171 = (ap_predicate_op171_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_173 = (ap_predicate_op173_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_175 = (ap_predicate_op175_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_74 = (ap_predicate_op74_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_75 = (ap_predicate_op75_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_76 = (ap_predicate_op76_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_77 = (ap_predicate_op77_load_state3 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op144_load_state4 = ((icmp_ln123_reg_846 == 1'd1) & (icmp_ln107_reg_842 == 1'd0));
end

always @ (*) begin
    ap_predicate_op145_load_state4 = ((icmp_ln123_reg_846 == 1'd1) & (icmp_ln107_reg_842 == 1'd0));
end

always @ (*) begin
    ap_predicate_op146_load_state4 = ((icmp_ln123_reg_846 == 1'd1) & (icmp_ln107_reg_842 == 1'd0));
end

always @ (*) begin
    ap_predicate_op147_load_state4 = ((icmp_ln123_reg_846 == 1'd1) & (icmp_ln107_reg_842 == 1'd0));
end

always @ (*) begin
    ap_predicate_op149_read_state4 = ((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0));
end

always @ (*) begin
    ap_predicate_op155_store_state4 = ((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (trunc_ln98_reg_838 == 2'd2));
end

always @ (*) begin
    ap_predicate_op157_store_state4 = ((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (trunc_ln98_reg_838 == 2'd1));
end

always @ (*) begin
    ap_predicate_op159_store_state4 = ((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (trunc_ln98_reg_838 == 2'd0));
end

always @ (*) begin
    ap_predicate_op161_store_state4 = ((1'd1 == and_ln153_reg_881) & (icmp_ln107_reg_842 == 1'd0) & (trunc_ln98_reg_838 == 2'd3));
end

always @ (*) begin
    ap_predicate_op169_store_state4 = ((icmp_ln107_reg_842 == 1'd1) & (trunc_ln98_reg_838 == 2'd2));
end

always @ (*) begin
    ap_predicate_op171_store_state4 = ((icmp_ln107_reg_842 == 1'd1) & (trunc_ln98_reg_838 == 2'd1));
end

always @ (*) begin
    ap_predicate_op173_store_state4 = ((icmp_ln107_reg_842 == 1'd1) & (trunc_ln98_reg_838 == 2'd0));
end

always @ (*) begin
    ap_predicate_op175_store_state4 = ((icmp_ln107_reg_842 == 1'd1) & (trunc_ln98_reg_838 == 2'd3));
end

always @ (*) begin
    ap_predicate_op177_write_state5 = ((icmp_ln123_reg_846_pp0_iter3_reg == 1'd1) & (icmp_ln107_reg_842_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op74_load_state3 = ((icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0));
end

always @ (*) begin
    ap_predicate_op75_load_state3 = ((icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0));
end

always @ (*) begin
    ap_predicate_op76_load_state3 = ((icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0));
end

always @ (*) begin
    ap_predicate_op77_load_state3 = ((icmp_ln123_fu_454_p2 == 1'd1) & (icmp_ln107_fu_448_p2 == 1'd0) & (icmp_ln104_reg_829 == 1'd0));
end

assign convInp_i31_din = p_0_reg_891;

assign count_simd_3_fu_511_p2 = (count_simd_fu_102 + 32'd1);

assign counter_internal_block_8_fu_635_p2 = (counter_internal_block_fu_110 + 32'd1);

assign counter_internal_block_9_fu_647_p3 = ((icmp_ln172_fu_641_p2[0:0] == 1'b1) ? 32'd0 : counter_internal_block_8_fu_635_p2);

assign current_line_in_block_fu_497_p2 = (shl_ln_fu_489_p3 + trunc_ln105_fu_440_p1);

assign grp_fu_279_p2 = (current_line_fu_106 + 32'd1);

assign grp_fu_285_p2 = ((grp_fu_279_p2 == 32'd24) ? 1'b1 : 1'b0);

assign grp_fu_291_p2 = (select_ln98_fu_432_p3 + 32'd1);

assign grp_fu_296_p2 = (current_block_write_11_fu_94 + 32'd1);

assign grp_fu_301_p2 = ((grp_fu_296_p2 == 32'd4) ? 1'b1 : 1'b0);

assign grp_fu_307_p3 = ((grp_fu_301_p2[0:0] == 1'b1) ? 32'd0 : grp_fu_296_p2);

assign i_fu_398_p3 = ((icmp_ln105_fu_386_p2[0:0] == 1'b1) ? 8'd1 : add_ln105_fu_392_p2);

assign icmp_ln104_fu_375_p2 = ((indvar_flatten_fu_82 == bound) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_386_p2 = ((i_09_fu_78 == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_448_p2 = ((inp_fu_98 < 32'd72) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_454_p2 = ((counter_internal_block_fu_110 < 32'd71) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_517_p2 = ((count_simd_3_fu_511_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_534_p2 = ((k_x_3_fu_528_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_550_p2 = ((k_y_3_fu_469_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln153_3_fu_593_p2 = ((select_ln98_fu_432_p3 < 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln153_fu_587_p2 = ((counter_internal_block_fu_110 < 32'd23) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_641_p2 = ((counter_internal_block_8_fu_635_p2 == 32'd71) ? 1'b1 : 1'b0);

assign inp_8_fu_660_p2 = (inp_fu_98 + 32'd1);

assign inp_9_fu_556_p3 = ((icmp_ln138_fu_550_p2[0:0] == 1'b1) ? 32'd0 : inp_fu_98);

assign inputBuf_1_address1 = zext_ln129_fu_503_p1;

assign inputBuf_2_address1 = zext_ln129_fu_503_p1;

assign inputBuf_3_address1 = zext_ln129_fu_503_p1;

assign inputBuf_address1 = zext_ln129_fu_503_p1;

assign k_x_3_fu_528_p2 = (k_x_fu_90 + 32'd1);

assign k_y_3_fu_469_p2 = (k_y_fu_86 + 32'd1);

assign k_y_4_fu_564_p3 = ((icmp_ln138_fu_550_p2[0:0] == 1'b1) ? 32'd0 : k_y_3_fu_469_p2);

assign p_0_fu_701_p9 = 'bx;

assign select_ln98_fu_432_p3 = ((icmp_ln105_reg_833[0:0] == 1'b1) ? 32'd0 : read_block_fu_74);

assign shl_ln_fu_489_p3 = {{trunc_ln128_fu_485_p1}, {3'd0}};

assign trunc_ln105_fu_440_p1 = count_simd_fu_102[4:0];

assign trunc_ln124_fu_475_p1 = k_y_3_fu_469_p2[1:0];

assign trunc_ln128_fu_485_p1 = k_x_fu_90[1:0];

assign trunc_ln98_fu_444_p1 = current_block_write_11_fu_94[1:0];

assign zext_ln110_fu_732_p1 = reg_315;

assign zext_ln129_fu_503_p1 = current_line_in_block_fu_497_p2;

assign zext_ln156_fu_724_p1 = reg_315;

endmodule //BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_3
