-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    inter0_233_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    inter0_233_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    inter0_233_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    inter0_233_empty_n : IN STD_LOGIC;
    inter0_233_read : OUT STD_LOGIC;
    convInp_i_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    convInp_i_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    convInp_i_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    convInp_i_full_n : IN STD_LOGIC;
    convInp_i_write : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (45 downto 0) );
end;


architecture behav of BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv46_1 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000001";
    constant ap_const_lv14_2004 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000100";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln107_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_reg_946 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op161_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal icmp_ln107_reg_904_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_908_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op189_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln104_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal inter0_233_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal convInp_i_blk_n : STD_LOGIC;
    signal reg_321 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln104_reg_891 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln105_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln105_reg_895 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln98_fu_462_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln98_reg_900 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln123_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln124_3_fu_494_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln124_3_reg_912 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_752_p11 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_0_reg_956 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal inputBuf_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_ce0 : STD_LOGIC;
    signal inputBuf_we0 : STD_LOGIC;
    signal inputBuf_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_ce1 : STD_LOGIC;
    signal inputBuf_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_1_ce0 : STD_LOGIC;
    signal inputBuf_1_we0 : STD_LOGIC;
    signal inputBuf_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_1_ce1 : STD_LOGIC;
    signal inputBuf_1_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_2_ce0 : STD_LOGIC;
    signal inputBuf_2_we0 : STD_LOGIC;
    signal inputBuf_2_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_2_ce1 : STD_LOGIC;
    signal inputBuf_2_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_3_ce0 : STD_LOGIC;
    signal inputBuf_3_we0 : STD_LOGIC;
    signal inputBuf_3_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_3_ce1 : STD_LOGIC;
    signal inputBuf_3_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln129_fu_506_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_fu_775_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln110_fu_783_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_block_fu_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln98_fu_446_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_010_fu_80 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal i_fu_409_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal indvar_flatten_fu_84 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    signal add_ln104_fu_391_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal ofm_y_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ofm_y_6_fu_600_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln135_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_x_fu_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ofm_x_3_fu_550_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_fu_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal inp_13_fu_592_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_12_fu_711_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_fu_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal k_y_5_fu_484_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_11_fu_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_313_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_fu_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal k_x_4_fu_514_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_fu_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_285_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_block_fu_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal counter_internal_block_12_fu_698_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_302_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_fu_403_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln124_fu_490_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln105_1_fu_458_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln105_fu_454_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal current_line_in_block_fu_500_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ofm_y_5_fu_580_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln144_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_634_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln153_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_4_fu_644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal counter_internal_block_11_fu_686_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln172_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_fu_752_p9 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op75_load_state3 : BOOLEAN;
    signal ap_enable_operation_75 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op156_load_state4 : BOOLEAN;
    signal ap_enable_operation_156 : BOOLEAN;
    signal ap_enable_state4_pp0_iter3_stage0 : BOOLEAN;
    signal ap_predicate_op171_store_state4 : BOOLEAN;
    signal ap_enable_operation_171 : BOOLEAN;
    signal ap_predicate_op185_store_state4 : BOOLEAN;
    signal ap_enable_operation_185 : BOOLEAN;
    signal ap_predicate_op76_load_state3 : BOOLEAN;
    signal ap_enable_operation_76 : BOOLEAN;
    signal ap_predicate_op157_load_state4 : BOOLEAN;
    signal ap_enable_operation_157 : BOOLEAN;
    signal ap_predicate_op169_store_state4 : BOOLEAN;
    signal ap_enable_operation_169 : BOOLEAN;
    signal ap_predicate_op183_store_state4 : BOOLEAN;
    signal ap_enable_operation_183 : BOOLEAN;
    signal ap_predicate_op77_load_state3 : BOOLEAN;
    signal ap_enable_operation_77 : BOOLEAN;
    signal ap_predicate_op158_load_state4 : BOOLEAN;
    signal ap_enable_operation_158 : BOOLEAN;
    signal ap_predicate_op167_store_state4 : BOOLEAN;
    signal ap_enable_operation_167 : BOOLEAN;
    signal ap_predicate_op181_store_state4 : BOOLEAN;
    signal ap_enable_operation_181 : BOOLEAN;
    signal ap_predicate_op78_load_state3 : BOOLEAN;
    signal ap_enable_operation_78 : BOOLEAN;
    signal ap_predicate_op159_load_state4 : BOOLEAN;
    signal ap_enable_operation_159 : BOOLEAN;
    signal ap_predicate_op173_store_state4 : BOOLEAN;
    signal ap_enable_operation_173 : BOOLEAN;
    signal ap_predicate_op187_store_state4 : BOOLEAN;
    signal ap_enable_operation_187 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_698 : BOOLEAN;
    signal ap_condition_702 : BOOLEAN;
    signal ap_condition_705 : BOOLEAN;
    signal ap_condition_708 : BOOLEAN;
    signal ap_condition_711 : BOOLEAN;
    signal ap_condition_714 : BOOLEAN;
    signal p_0_fu_752_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_752_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_752_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_752_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component BlackBoxJam_sparsemux_9_2_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2_inputBbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component BlackBoxJam_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    inputBuf_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2_inputBbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_address0,
        ce0 => inputBuf_ce0,
        we0 => inputBuf_we0,
        d0 => inter0_233_dout,
        address1 => inputBuf_address1,
        ce1 => inputBuf_ce1,
        q1 => inputBuf_q1);

    inputBuf_1_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2_inputBbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_address0,
        ce0 => inputBuf_1_ce0,
        we0 => inputBuf_1_we0,
        d0 => inter0_233_dout,
        address1 => inputBuf_1_address1,
        ce1 => inputBuf_1_ce1,
        q1 => inputBuf_1_q1);

    inputBuf_2_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2_inputBbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_address0,
        ce0 => inputBuf_2_ce0,
        we0 => inputBuf_2_we0,
        d0 => inter0_233_dout,
        address1 => inputBuf_2_address1,
        ce1 => inputBuf_2_ce1,
        q1 => inputBuf_2_q1);

    inputBuf_3_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_2_inputBbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_address0,
        ce0 => inputBuf_3_ce0,
        we0 => inputBuf_3_we0,
        d0 => inter0_233_dout,
        address1 => inputBuf_3_address1,
        ce1 => inputBuf_3_ce1,
        q1 => inputBuf_3_q1);

    sparsemux_9_2_24_1_1_U28 : component BlackBoxJam_sparsemux_9_2_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 24,
        CASE1 => "01",
        din1_WIDTH => 24,
        CASE2 => "10",
        din2_WIDTH => 24,
        CASE3 => "11",
        din3_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 2,
        dout_WIDTH => 24)
    port map (
        din0 => inputBuf_q1,
        din1 => inputBuf_1_q1,
        din2 => inputBuf_2_q1,
        din3 => inputBuf_3_q1,
        def => p_0_fu_752_p9,
        sel => add_ln124_3_reg_912,
        dout => p_0_fu_752_p11);

    flow_control_loop_pipe_sequential_init_U : component BlackBoxJam_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    counter_internal_block_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then 
                counter_internal_block_fu_116 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0))) then 
                counter_internal_block_fu_116 <= counter_internal_block_12_fu_698_p3;
            end if; 
        end if;
    end process;

    current_block_write_11_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                current_block_write_11_fu_104 <= ap_const_lv32_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then 
                current_block_write_11_fu_104 <= grp_fu_313_p3;
            end if; 
        end if;
    end process;

    current_line_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then 
                current_line_fu_112 <= ap_const_lv32_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then 
                current_line_fu_112 <= grp_fu_285_p2;
            end if; 
        end if;
    end process;

    i_010_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_010_fu_80 <= ap_const_lv14_0;
                elsif (((icmp_ln104_fu_386_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_010_fu_80 <= i_fu_409_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_84 <= ap_const_lv46_0;
                elsif (((icmp_ln104_fu_386_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_84 <= add_ln104_fu_391_p2;
                end if;
            end if; 
        end if;
    end process;

    inp_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    inp_fu_96 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_702)) then 
                    inp_fu_96 <= inp_12_fu_711_p2;
                elsif ((ap_const_boolean_1 = ap_condition_698)) then 
                    inp_fu_96 <= inp_13_fu_592_p3;
                end if;
            end if; 
        end if;
    end process;

    k_x_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_531_p2 = ap_const_lv1_0) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_556_p2 = ap_const_lv1_0) and (icmp_ln138_fu_531_p2 = ap_const_lv1_1) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_556_p2 = ap_const_lv1_1) and (icmp_ln138_fu_531_p2 = ap_const_lv1_1) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 
    = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                k_x_fu_108 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_fu_520_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0))) then 
                k_x_fu_108 <= k_x_4_fu_514_p2;
            end if; 
        end if;
    end process;

    k_y_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_531_p2 = ap_const_lv1_1) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                k_y_fu_100 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_531_p2 = ap_const_lv1_0) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0))) then 
                k_y_fu_100 <= k_y_5_fu_484_p2;
            end if; 
        end if;
    end process;

    ofm_x_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_556_p2 = ap_const_lv1_1) and (icmp_ln138_fu_531_p2 = ap_const_lv1_1) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ofm_x_fu_92 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_556_p2 = ap_const_lv1_0) and (icmp_ln138_fu_531_p2 = ap_const_lv1_1) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0))) then 
                ofm_x_fu_92 <= ofm_x_3_fu_550_p2;
            end if; 
        end if;
    end process;

    ofm_y_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ofm_y_fu_88 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_698)) then 
                    ofm_y_fu_88 <= ofm_y_6_fu_600_p3;
                end if;
            end if; 
        end if;
    end process;

    read_block_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                read_block_fu_76 <= ap_const_lv32_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then 
                read_block_fu_76 <= grp_fu_297_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_291_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then 
                read_block_fu_76 <= select_ln98_fu_446_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln124_3_reg_912 <= add_ln124_3_fu_494_p2;
                and_ln153_reg_946 <= and_ln153_fu_650_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln107_reg_904 <= icmp_ln107_fu_466_p2;
                icmp_ln107_reg_904_pp0_iter3_reg <= icmp_ln107_reg_904;
                icmp_ln123_reg_908 <= icmp_ln123_fu_472_p2;
                icmp_ln123_reg_908_pp0_iter3_reg <= icmp_ln123_reg_908;
                p_0_reg_956 <= p_0_fu_752_p11;
                trunc_ln98_reg_900 <= trunc_ln98_fu_462_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln104_reg_891 <= icmp_ln104_fu_386_p2;
                icmp_ln105_reg_895 <= icmp_ln105_fu_397_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_650_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0)))) then
                reg_321 <= current_line_fu_112;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln104_fu_391_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_84) + unsigned(ap_const_lv46_1));
    add_ln105_fu_403_p2 <= std_logic_vector(unsigned(i_010_fu_80) + unsigned(ap_const_lv14_1));
    add_ln124_3_fu_494_p2 <= std_logic_vector(unsigned(trunc_ln124_fu_490_p1) + unsigned(trunc_ln98_fu_462_p1));
    and_ln153_fu_650_p2 <= (icmp_ln153_fu_628_p2 and icmp_ln153_4_fu_644_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state4_pp0_stage0_iter3, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state4_pp0_stage0_iter3, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state4_pp0_stage0_iter3, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(inter0_233_empty_n, icmp_ln107_reg_904, ap_predicate_op161_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (((icmp_ln107_reg_904 = ap_const_lv1_1) and (inter0_233_empty_n = ap_const_logic_0)) or ((ap_predicate_op161_read_state4 = ap_const_boolean_1) and (inter0_233_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(convInp_i_full_n, ap_predicate_op189_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((ap_predicate_op189_write_state5 = ap_const_boolean_1) and (convInp_i_full_n = ap_const_logic_0));
    end process;


    ap_condition_698_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln104_reg_891, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2, icmp_ln135_fu_520_p2, icmp_ln138_fu_531_p2, icmp_ln141_fu_556_p2)
    begin
                ap_condition_698 <= ((icmp_ln141_fu_556_p2 = ap_const_lv1_1) and (icmp_ln138_fu_531_p2 = ap_const_lv1_1) and (icmp_ln135_fu_520_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0));
    end process;


    ap_condition_702_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln104_reg_891, icmp_ln107_fu_466_p2)
    begin
                ap_condition_702 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_891 = ap_const_lv1_0));
    end process;


    ap_condition_705_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_900)
    begin
                ap_condition_705 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_1));
    end process;


    ap_condition_708_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_900)
    begin
                ap_condition_708 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_2));
    end process;


    ap_condition_711_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_900)
    begin
                ap_condition_711 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_3));
    end process;


    ap_condition_714_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_900)
    begin
                ap_condition_714 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln104_fu_386_p2)
    begin
        if (((icmp_ln104_fu_386_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln104_reg_891)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln104_reg_891 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_156_assign_proc : process(ap_predicate_op156_load_state4)
    begin
                ap_enable_operation_156 <= (ap_predicate_op156_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_157_assign_proc : process(ap_predicate_op157_load_state4)
    begin
                ap_enable_operation_157 <= (ap_predicate_op157_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_158_assign_proc : process(ap_predicate_op158_load_state4)
    begin
                ap_enable_operation_158 <= (ap_predicate_op158_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_159_assign_proc : process(ap_predicate_op159_load_state4)
    begin
                ap_enable_operation_159 <= (ap_predicate_op159_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_167_assign_proc : process(ap_predicate_op167_store_state4)
    begin
                ap_enable_operation_167 <= (ap_predicate_op167_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_169_assign_proc : process(ap_predicate_op169_store_state4)
    begin
                ap_enable_operation_169 <= (ap_predicate_op169_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_171_assign_proc : process(ap_predicate_op171_store_state4)
    begin
                ap_enable_operation_171 <= (ap_predicate_op171_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_173_assign_proc : process(ap_predicate_op173_store_state4)
    begin
                ap_enable_operation_173 <= (ap_predicate_op173_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_181_assign_proc : process(ap_predicate_op181_store_state4)
    begin
                ap_enable_operation_181 <= (ap_predicate_op181_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_183_assign_proc : process(ap_predicate_op183_store_state4)
    begin
                ap_enable_operation_183 <= (ap_predicate_op183_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_185_assign_proc : process(ap_predicate_op185_store_state4)
    begin
                ap_enable_operation_185 <= (ap_predicate_op185_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_187_assign_proc : process(ap_predicate_op187_store_state4)
    begin
                ap_enable_operation_187 <= (ap_predicate_op187_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_75_assign_proc : process(ap_predicate_op75_load_state3)
    begin
                ap_enable_operation_75 <= (ap_predicate_op75_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_76_assign_proc : process(ap_predicate_op76_load_state3)
    begin
                ap_enable_operation_76 <= (ap_predicate_op76_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_77_assign_proc : process(ap_predicate_op77_load_state3)
    begin
                ap_enable_operation_77 <= (ap_predicate_op77_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_78_assign_proc : process(ap_predicate_op78_load_state3)
    begin
                ap_enable_operation_78 <= (ap_predicate_op78_load_state3 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state4_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_predicate_op156_load_state4_assign_proc : process(icmp_ln107_reg_904, icmp_ln123_reg_908)
    begin
                ap_predicate_op156_load_state4 <= ((icmp_ln123_reg_908 = ap_const_lv1_1) and (icmp_ln107_reg_904 = ap_const_lv1_0));
    end process;


    ap_predicate_op157_load_state4_assign_proc : process(icmp_ln107_reg_904, icmp_ln123_reg_908)
    begin
                ap_predicate_op157_load_state4 <= ((icmp_ln123_reg_908 = ap_const_lv1_1) and (icmp_ln107_reg_904 = ap_const_lv1_0));
    end process;


    ap_predicate_op158_load_state4_assign_proc : process(icmp_ln107_reg_904, icmp_ln123_reg_908)
    begin
                ap_predicate_op158_load_state4 <= ((icmp_ln123_reg_908 = ap_const_lv1_1) and (icmp_ln107_reg_904 = ap_const_lv1_0));
    end process;


    ap_predicate_op159_load_state4_assign_proc : process(icmp_ln107_reg_904, icmp_ln123_reg_908)
    begin
                ap_predicate_op159_load_state4 <= ((icmp_ln123_reg_908 = ap_const_lv1_1) and (icmp_ln107_reg_904 = ap_const_lv1_0));
    end process;


    ap_predicate_op161_read_state4_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946)
    begin
                ap_predicate_op161_read_state4 <= ((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0));
    end process;


    ap_predicate_op167_store_state4_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, trunc_ln98_reg_900)
    begin
                ap_predicate_op167_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (trunc_ln98_reg_900 = ap_const_lv2_2));
    end process;


    ap_predicate_op169_store_state4_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, trunc_ln98_reg_900)
    begin
                ap_predicate_op169_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (trunc_ln98_reg_900 = ap_const_lv2_1));
    end process;


    ap_predicate_op171_store_state4_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, trunc_ln98_reg_900)
    begin
                ap_predicate_op171_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (trunc_ln98_reg_900 = ap_const_lv2_0));
    end process;


    ap_predicate_op173_store_state4_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, trunc_ln98_reg_900)
    begin
                ap_predicate_op173_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (trunc_ln98_reg_900 = ap_const_lv2_3));
    end process;


    ap_predicate_op181_store_state4_assign_proc : process(icmp_ln107_reg_904, trunc_ln98_reg_900)
    begin
                ap_predicate_op181_store_state4 <= ((icmp_ln107_reg_904 = ap_const_lv1_1) and (trunc_ln98_reg_900 = ap_const_lv2_2));
    end process;


    ap_predicate_op183_store_state4_assign_proc : process(icmp_ln107_reg_904, trunc_ln98_reg_900)
    begin
                ap_predicate_op183_store_state4 <= ((icmp_ln107_reg_904 = ap_const_lv1_1) and (trunc_ln98_reg_900 = ap_const_lv2_1));
    end process;


    ap_predicate_op185_store_state4_assign_proc : process(icmp_ln107_reg_904, trunc_ln98_reg_900)
    begin
                ap_predicate_op185_store_state4 <= ((icmp_ln107_reg_904 = ap_const_lv1_1) and (trunc_ln98_reg_900 = ap_const_lv2_0));
    end process;


    ap_predicate_op187_store_state4_assign_proc : process(icmp_ln107_reg_904, trunc_ln98_reg_900)
    begin
                ap_predicate_op187_store_state4 <= ((icmp_ln107_reg_904 = ap_const_lv1_1) and (trunc_ln98_reg_900 = ap_const_lv2_3));
    end process;


    ap_predicate_op189_write_state5_assign_proc : process(icmp_ln107_reg_904_pp0_iter3_reg, icmp_ln123_reg_908_pp0_iter3_reg)
    begin
                ap_predicate_op189_write_state5 <= ((icmp_ln123_reg_908_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln107_reg_904_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op75_load_state3_assign_proc : process(icmp_ln104_reg_891, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op75_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0));
    end process;


    ap_predicate_op76_load_state3_assign_proc : process(icmp_ln104_reg_891, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op76_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0));
    end process;


    ap_predicate_op77_load_state3_assign_proc : process(icmp_ln104_reg_891, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op77_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0));
    end process;


    ap_predicate_op78_load_state3_assign_proc : process(icmp_ln104_reg_891, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op78_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_891 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    convInp_i_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, convInp_i_full_n, ap_predicate_op189_write_state5, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op189_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            convInp_i_blk_n <= convInp_i_full_n;
        else 
            convInp_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    convInp_i_din <= p_0_reg_956;

    convInp_i_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op189_write_state5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op189_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            convInp_i_write <= ap_const_logic_1;
        else 
            convInp_i_write <= ap_const_logic_0;
        end if; 
    end process;

    counter_internal_block_11_fu_686_p2 <= std_logic_vector(unsigned(counter_internal_block_fu_116) + unsigned(ap_const_lv32_1));
    counter_internal_block_12_fu_698_p3 <= 
        ap_const_lv32_0 when (icmp_ln172_fu_692_p2(0) = '1') else 
        counter_internal_block_11_fu_686_p2;
    current_line_in_block_fu_500_p2 <= std_logic_vector(unsigned(trunc_ln105_1_fu_458_p1) + unsigned(trunc_ln105_fu_454_p1));
    grp_fu_285_p2 <= std_logic_vector(unsigned(current_line_fu_112) + unsigned(ap_const_lv32_1));
    grp_fu_291_p2 <= "1" when (grp_fu_285_p2 = ap_const_lv32_20) else "0";
    grp_fu_297_p2 <= std_logic_vector(unsigned(select_ln98_fu_446_p3) + unsigned(ap_const_lv32_1));
    grp_fu_302_p2 <= std_logic_vector(unsigned(current_block_write_11_fu_104) + unsigned(ap_const_lv32_1));
    grp_fu_307_p2 <= "1" when (grp_fu_302_p2 = ap_const_lv32_4) else "0";
    grp_fu_313_p3 <= 
        ap_const_lv32_0 when (grp_fu_307_p2(0) = '1') else 
        grp_fu_302_p2;
    i_fu_409_p3 <= 
        ap_const_lv14_1 when (icmp_ln105_fu_397_p2(0) = '1') else 
        add_ln105_fu_403_p2;
    icmp_ln104_fu_386_p2 <= "1" when (indvar_flatten_fu_84 = bound) else "0";
    icmp_ln105_fu_397_p2 <= "1" when (i_010_fu_80 = ap_const_lv14_2004) else "0";
    icmp_ln107_fu_466_p2 <= "1" when (unsigned(inp_fu_96) < unsigned(ap_const_lv32_60)) else "0";
    icmp_ln123_fu_472_p2 <= "1" when (unsigned(counter_internal_block_fu_116) < unsigned(ap_const_lv32_10D)) else "0";
    icmp_ln135_fu_520_p2 <= "1" when (k_x_4_fu_514_p2 = ap_const_lv32_3) else "0";
    icmp_ln138_fu_531_p2 <= "1" when (k_y_5_fu_484_p2 = ap_const_lv32_3) else "0";
    icmp_ln141_fu_556_p2 <= "1" when (ofm_x_3_fu_550_p2 = ap_const_lv32_1E) else "0";
    icmp_ln144_fu_586_p2 <= "1" when (ofm_y_5_fu_580_p2 = ap_const_lv32_1E) else "0";
    icmp_ln153_4_fu_644_p2 <= "1" when (tmp_fu_634_p4 = ap_const_lv27_0) else "0";
    icmp_ln153_fu_628_p2 <= "1" when (unsigned(counter_internal_block_fu_116) < unsigned(ap_const_lv32_1F)) else "0";
    icmp_ln172_fu_692_p2 <= "1" when (counter_internal_block_11_fu_686_p2 = ap_const_lv32_10D) else "0";
    inp_12_fu_711_p2 <= std_logic_vector(unsigned(inp_fu_96) + unsigned(ap_const_lv32_1));
    inp_13_fu_592_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_586_p2(0) = '1') else 
        inp_fu_96;

    inputBuf_1_address0_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, zext_ln156_fu_775_p1, zext_ln110_fu_783_p1, ap_condition_705)
    begin
        if ((ap_const_boolean_1 = ap_condition_705)) then
            if ((icmp_ln107_reg_904 = ap_const_lv1_1)) then 
                inputBuf_1_address0 <= zext_ln110_fu_783_p1(5 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0))) then 
                inputBuf_1_address0 <= zext_ln156_fu_775_p1(5 - 1 downto 0);
            else 
                inputBuf_1_address0 <= "XXXXX";
            end if;
        else 
            inputBuf_1_address0 <= "XXXXX";
        end if; 
    end process;

    inputBuf_1_address1 <= zext_ln129_fu_506_p1(5 - 1 downto 0);

    inputBuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_1)))) then 
            inputBuf_1_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_1_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_1)))) then 
            inputBuf_1_we0 <= ap_const_logic_1;
        else 
            inputBuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_address0_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, zext_ln156_fu_775_p1, zext_ln110_fu_783_p1, ap_condition_708)
    begin
        if ((ap_const_boolean_1 = ap_condition_708)) then
            if ((icmp_ln107_reg_904 = ap_const_lv1_1)) then 
                inputBuf_2_address0 <= zext_ln110_fu_783_p1(5 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0))) then 
                inputBuf_2_address0 <= zext_ln156_fu_775_p1(5 - 1 downto 0);
            else 
                inputBuf_2_address0 <= "XXXXX";
            end if;
        else 
            inputBuf_2_address0 <= "XXXXX";
        end if; 
    end process;

    inputBuf_2_address1 <= zext_ln129_fu_506_p1(5 - 1 downto 0);

    inputBuf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_2)))) then 
            inputBuf_2_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_2_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_2)))) then 
            inputBuf_2_we0 <= ap_const_logic_1;
        else 
            inputBuf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_address0_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, zext_ln156_fu_775_p1, zext_ln110_fu_783_p1, ap_condition_711)
    begin
        if ((ap_const_boolean_1 = ap_condition_711)) then
            if ((icmp_ln107_reg_904 = ap_const_lv1_1)) then 
                inputBuf_3_address0 <= zext_ln110_fu_783_p1(5 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0))) then 
                inputBuf_3_address0 <= zext_ln156_fu_775_p1(5 - 1 downto 0);
            else 
                inputBuf_3_address0 <= "XXXXX";
            end if;
        else 
            inputBuf_3_address0 <= "XXXXX";
        end if; 
    end process;

    inputBuf_3_address1 <= zext_ln129_fu_506_p1(5 - 1 downto 0);

    inputBuf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_3)))) then 
            inputBuf_3_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_3_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_3)))) then 
            inputBuf_3_we0 <= ap_const_logic_1;
        else 
            inputBuf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_address0_assign_proc : process(icmp_ln107_reg_904, and_ln153_reg_946, zext_ln156_fu_775_p1, zext_ln110_fu_783_p1, ap_condition_714)
    begin
        if ((ap_const_boolean_1 = ap_condition_714)) then
            if ((icmp_ln107_reg_904 = ap_const_lv1_1)) then 
                inputBuf_address0 <= zext_ln110_fu_783_p1(5 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0))) then 
                inputBuf_address0 <= zext_ln156_fu_775_p1(5 - 1 downto 0);
            else 
                inputBuf_address0 <= "XXXXX";
            end if;
        else 
            inputBuf_address0 <= "XXXXX";
        end if; 
    end process;

    inputBuf_address1 <= zext_ln129_fu_506_p1(5 - 1 downto 0);

    inputBuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_0)))) then 
            inputBuf_ce0 <= ap_const_logic_1;
        else 
            inputBuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_ce1 <= ap_const_logic_1;
        else 
            inputBuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, and_ln153_reg_946, ap_block_pp0_stage0_11001, trunc_ln98_reg_900)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_946) and (icmp_ln107_reg_904 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_900 = ap_const_lv2_0)))) then 
            inputBuf_we0 <= ap_const_logic_1;
        else 
            inputBuf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inter0_233_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, inter0_233_empty_n, icmp_ln107_reg_904, ap_predicate_op161_read_state4, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op161_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            inter0_233_blk_n <= inter0_233_empty_n;
        else 
            inter0_233_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    inter0_233_read_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_904, ap_predicate_op161_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_904 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op161_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            inter0_233_read <= ap_const_logic_1;
        else 
            inter0_233_read <= ap_const_logic_0;
        end if; 
    end process;

    k_x_4_fu_514_p2 <= std_logic_vector(unsigned(k_x_fu_108) + unsigned(ap_const_lv32_1));
    k_y_5_fu_484_p2 <= std_logic_vector(unsigned(k_y_fu_100) + unsigned(ap_const_lv32_1));
    ofm_x_3_fu_550_p2 <= std_logic_vector(unsigned(ofm_x_fu_92) + unsigned(ap_const_lv32_1));
    ofm_y_5_fu_580_p2 <= std_logic_vector(unsigned(ofm_y_fu_88) + unsigned(ap_const_lv32_1));
    ofm_y_6_fu_600_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_586_p2(0) = '1') else 
        ofm_y_5_fu_580_p2;
    p_0_fu_752_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln98_fu_446_p3 <= 
        ap_const_lv32_0 when (icmp_ln105_reg_895(0) = '1') else 
        read_block_fu_76;
    tmp_fu_634_p4 <= select_ln98_fu_446_p3(31 downto 5);
    trunc_ln105_1_fu_458_p1 <= ofm_x_fu_92(5 - 1 downto 0);
    trunc_ln105_fu_454_p1 <= k_x_fu_108(5 - 1 downto 0);
    trunc_ln124_fu_490_p1 <= k_y_5_fu_484_p2(2 - 1 downto 0);
    trunc_ln98_fu_462_p1 <= current_block_write_11_fu_104(2 - 1 downto 0);
    zext_ln110_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_321),64));
    zext_ln129_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_in_block_fu_500_p2),64));
    zext_ln156_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_321),64));
end behav;
