<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>DoCompute_Block_ZN25WidthAdjustedOutputStreamILj16ELj128ELj1152EED2Ev_exit_loop</name>
      <module_structure>Sequential</module_structure>
      <ret_bitwidth>96</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>numReps</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1860848640</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>26</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>9</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_2">
          <Value>
            <Obj>
              <type>0</type>
              <id>2</id>
              <name>numReps_read</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>4</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>srl</implIndex>
              <coreName>FIFO_SRL</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>81</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>26</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>13</item>
            <item>14</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>3.63</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>3</id>
              <name>trunc_ln265</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>trunc_ln265_fu_20_p1</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>539764286</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>23</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>15</item>
          </oprand_edges>
          <opcode>trunc</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>4</id>
              <name>tmp</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_fu_24_p3</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1109404710</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>17</item>
            <item>18</item>
            <item>20</item>
          </oprand_edges>
          <opcode>bitconcatenate</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>5</id>
              <name>totalIters</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>totalIters</originalName>
              <rtlName>totalIters_fu_32_p3</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1109404710</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>22</item>
            <item>23</item>
            <item>25</item>
          </oprand_edges>
          <opcode>bitconcatenate</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>6</id>
              <name>totalIters_1</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>totalIters</originalName>
              <rtlName>totalIters_1_fu_40_p2</rtlName>
              <control>auto</control>
              <opType>add</opType>
              <implIndex>fabric</implIndex>
              <coreName>Adder</coreName>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>26</item>
            <item>27</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>2.55</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>7</id>
              <name>mrv_i</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>0</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>29</item>
            <item>30</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>mrv_1_i</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>539764286</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>31</item>
            <item>32</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>7</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>9</id>
              <name>mrv_2_i</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>0</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>34</item>
          </oprand_edges>
          <opcode>insertvalue</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>8</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>10</id>
              <name>_ln265</name>
              <fileName>../streamtools.h</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>265</lineNumber>
              <contextFuncName>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</contextFuncName>
              <contextNormFuncName>StreamingDataWidthConverter_Batch_128_32_144_s</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>E:\Tai_lieu\DATN\vitis\hw</first>
                  <second>
                    <count>4</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>../convlayer.h</first>
                        <second>ConvLayer_Batch&amp;lt;3, 128, 12, 128, 10, 32, 16, Recast&amp;lt;XnorMul&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Identity, 128, 128, BinaryWeights&amp;lt;32, 16, 288&amp;gt;, ThresholdsActivation&amp;lt;8, 16, 1, ap_int&amp;lt;16&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_int&amp;lt;16&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
                      </first>
                      <second>113</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>StreamingDataWidthConverter_Batch&amp;lt;128, 32, 144&amp;gt;</second>
                      </first>
                      <second>265</second>
                    </item>
                    <item>
                      <first>
                        <first>../streamtools.h</first>
                        <second>WidthAdjustedInputStream</second>
                      </first>
                      <second>720</second>
                    </item>
                    <item>
                      <first>
                        <first>../top.cpp</first>
                        <second>DoCompute</second>
                      </first>
                      <second>134</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>539764286</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>35</item>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>9</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_11">
          <Value>
            <Obj>
              <type>2</type>
              <id>19</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1953853549</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>9</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_12">
          <Value>
            <Obj>
              <type>2</type>
              <id>24</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1953853549</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>6</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_13">
          <Value>
            <Obj>
              <type>2</type>
              <id>28</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1953853549</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>96</bitwidth>
          </Value>
          <const_type>5</const_type>
          <content>&lt;undef&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_14">
          <Obj>
            <type>3</type>
            <id>11</id>
            <name>DoCompute_Block__ZN25WidthAdjustedOutputStreamILj16ELj128ELj1152EED2Ev.exit.loop</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>660890721</coreId>
            <rtlModuleName/>
          </Obj>
          <node_objs>
            <count>9</count>
            <item_version>0</item_version>
            <item>2</item>
            <item>3</item>
            <item>4</item>
            <item>5</item>
            <item>6</item>
            <item>7</item>
            <item>8</item>
            <item>9</item>
            <item>10</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>15</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_15">
          <id>14</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>2</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_16">
          <id>15</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>3</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_17">
          <id>18</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>4</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_18">
          <id>20</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>4</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_19">
          <id>23</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>5</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_20">
          <id>25</id>
          <edge_type>1</edge_type>
          <source_obj>24</source_obj>
          <sink_obj>5</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_21">
          <id>26</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>6</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_22">
          <id>27</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>6</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>29</id>
          <edge_type>1</edge_type>
          <source_obj>28</source_obj>
          <sink_obj>7</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>30</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>7</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>31</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>8</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>32</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>8</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>33</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>9</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>34</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>9</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>35</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>10</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_30">
        <mId>1</mId>
        <mTag>DoCompute_Block__ZN25WidthAdjustedOutputStreamILj16ELj128ELj1152EED2Ev.exit.loop</mTag>
        <mNormTag>DoCompute_Block_ZN25WidthAdjustedOutputStreamILj16ELj128ELj1152EED2Ev_exit_loop</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>0</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_31">
      <states class_id="25" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_32">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>9</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_33">
              <id>2</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_34">
              <id>3</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_35">
              <id>4</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_36">
              <id>5</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_37">
              <id>6</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_38">
              <id>7</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_39">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_40">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_41">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </transitions>
    </fsm>
    <res class_id="30" tracking_level="1" version="0" object_id="_42">
      <dp_component_resource class_id="31" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_resource>
      <dp_expression_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="32" tracking_level="0" version="0">
          <first>ap_block_state1 ( or ) </first>
          <second class_id="33" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="34" tracking_level="0" version="0">
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>totalIters_1_fu_40_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>32</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>32</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>39</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>4</count>
        <item_version>0</item_version>
        <item>
          <first>ap_done</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_0</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>26</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>52</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_1</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>26</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>52</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_2</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>23</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>46</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>5</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_0_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>6</second>
            </item>
            <item>
              <first>FF</first>
              <second>26</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_1_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>6</second>
            </item>
            <item>
              <first>FF</first>
              <second>26</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_return_2_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>9</second>
            </item>
            <item>
              <first>FF</first>
              <second>23</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_dsp_resource>
      <dp_component_map class_id="35" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_map>
      <dp_expression_map>
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>totalIters_1_fu_40_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>6</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="37" tracking_level="0" version="0">
      <count>9</count>
      <item_version>0</item_version>
      <item class_id="38" tracking_level="0" version="0">
        <first>2</first>
        <second class_id="39" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>3</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>4</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>5</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>6</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>7</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>8</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>9</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>10</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="40" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="41" tracking_level="0" version="0">
        <first>11</first>
        <second class_id="42" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="43" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="44" tracking_level="0" version="0">
      <count>8</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>14</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>2</item>
        </second>
      </item>
      <item>
        <first>20</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>3</item>
        </second>
      </item>
      <item>
        <first>24</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>4</item>
        </second>
      </item>
      <item>
        <first>32</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>40</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>52</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>58</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="47" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="48" tracking_level="0" version="0">
        <first>mrv_1_i_fu_52</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>mrv_2_i_fu_58</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>mrv_i_fu_46</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>tmp_fu_24</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>4</item>
        </second>
      </item>
      <item>
        <first>totalIters_1_fu_40</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>totalIters_fu_32</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>trunc_ln265_fu_20</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>3</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>numReps_read_read_fu_14</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>2</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>ap_return_0</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>ap_return_1</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>ap_return_2</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
    </return_ports>
    <dp_mem_port_nodes class_id="49" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="50" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="51" tracking_level="0" version="0">
        <first>numReps</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>2</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>2</first>
        <second>
          <first>666</first>
          <second>10</second>
        </second>
      </item>
      <item>
        <first>6</first>
        <second>
          <first>8</first>
          <second>4</second>
        </second>
      </item>
    </node2core>
  </syndb>
</boost_serialization>
