<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>DoCompute_Block_entry5993_proc</name>
		<module_structure>Sequential</module_structure>
		<ret_bitwidth>60</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>1</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>numReps</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>807419168</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>5</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_2">
				<Value>
					<Obj>
						<type>0</type>
						<id>2</id>
						<name>numReps_read</name>
						<fileName>../convlayer.h</fileName>
						<fileDirectory>E:\Tai_lieu\DATN\vitis\hw</fileDirectory>
						<lineNumber>118</lineNumber>
						<contextFuncName>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</contextFuncName>
						<contextNormFuncName>ConvLayer_Batch_3_3_32_64_30_3_16_Slice_ap_fixed_8_1_AP_TRN_AP_SAT_0_8_Slice_ap_uint_1_1_Recast_Binary_24_64_BinaryWeights_3_16_36_ThresholdsActivation_4_16_1_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_uint_1_0_std_less_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_resource_lut_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="10" tracking_level="0" version="0">
								<first>E:\Tai_lieu\DATN\vitis\hw</first>
								<second class_id="11" tracking_level="0" version="0">
									<count>2</count>
									<item_version>0</item_version>
									<item class_id="12" tracking_level="0" version="0">
										<first class_id="13" tracking_level="0" version="0">
											<first>../convlayer.h</first>
											<second>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
										</first>
										<second>118</second>
									</item>
									<item>
										<first>
											<first>../top.cpp</first>
											<second>DoCompute</second>
										</first>
										<second>129</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control>auto</control>
						<opType>fifo</opType>
						<implIndex>srl</implIndex>
						<coreName>FIFO_SRL</coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>81</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>9</item>
					<item>10</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>3.63</m_delay>
				<m_topoIndex>1</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_3">
				<Value>
					<Obj>
						<type>0</type>
						<id>3</id>
						<name>mul_ln118</name>
						<fileName>../convlayer.h</fileName>
						<fileDirectory>E:\Tai_lieu\DATN\vitis\hw</fileDirectory>
						<lineNumber>118</lineNumber>
						<contextFuncName>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</contextFuncName>
						<contextNormFuncName>ConvLayer_Batch_3_3_32_64_30_3_16_Slice_ap_fixed_8_1_AP_TRN_AP_SAT_0_8_Slice_ap_uint_1_1_Recast_Binary_24_64_BinaryWeights_3_16_36_ThresholdsActivation_4_16_1_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_uint_1_0_std_less_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_resource_lut_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>E:\Tai_lieu\DATN\vitis\hw</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>../convlayer.h</first>
											<second>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
										</first>
										<second>118</second>
									</item>
									<item>
										<first>
											<first>../top.cpp</first>
											<second>DoCompute</second>
										</first>
										<second>129</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control>auto</control>
						<opType>mul</opType>
						<implIndex>auto</implIndex>
						<coreName>Multiplier</coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>3</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>11</item>
					<item>13</item>
				</oprand_edges>
				<opcode>mul</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>6.91</m_delay>
				<m_topoIndex>2</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>4</id>
						<name>mrv_i</name>
						<fileName>../convlayer.h</fileName>
						<fileDirectory>E:\Tai_lieu\DATN\vitis\hw</fileDirectory>
						<lineNumber>118</lineNumber>
						<contextFuncName>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</contextFuncName>
						<contextNormFuncName>ConvLayer_Batch_3_3_32_64_30_3_16_Slice_ap_fixed_8_1_AP_TRN_AP_SAT_0_8_Slice_ap_uint_1_1_Recast_Binary_24_64_BinaryWeights_3_16_36_ThresholdsActivation_4_16_1_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_uint_1_0_std_less_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_resource_lut_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>E:\Tai_lieu\DATN\vitis\hw</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>../convlayer.h</first>
											<second>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
										</first>
										<second>118</second>
									</item>
									<item>
										<first>
											<first>../top.cpp</first>
											<second>DoCompute</second>
										</first>
										<second>129</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1109404710</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>60</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>15</item>
					<item>16</item>
				</oprand_edges>
				<opcode>insertvalue</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>3</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>5</id>
						<name>mrv_1_i</name>
						<fileName>../convlayer.h</fileName>
						<fileDirectory>E:\Tai_lieu\DATN\vitis\hw</fileDirectory>
						<lineNumber>118</lineNumber>
						<contextFuncName>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</contextFuncName>
						<contextNormFuncName>ConvLayer_Batch_3_3_32_64_30_3_16_Slice_ap_fixed_8_1_AP_TRN_AP_SAT_0_8_Slice_ap_uint_1_1_Recast_Binary_24_64_BinaryWeights_3_16_36_ThresholdsActivation_4_16_1_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_uint_1_0_std_less_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_resource_lut_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>E:\Tai_lieu\DATN\vitis\hw</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>../convlayer.h</first>
											<second>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
										</first>
										<second>118</second>
									</item>
									<item>
										<first>
											<first>../top.cpp</first>
											<second>DoCompute</second>
										</first>
										<second>129</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>539764286</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>60</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>17</item>
					<item>18</item>
				</oprand_edges>
				<opcode>insertvalue</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>4</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>6</id>
						<name>_ln118</name>
						<fileName>../convlayer.h</fileName>
						<fileDirectory>E:\Tai_lieu\DATN\vitis\hw</fileDirectory>
						<lineNumber>118</lineNumber>
						<contextFuncName>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</contextFuncName>
						<contextNormFuncName>ConvLayer_Batch_3_3_32_64_30_3_16_Slice_ap_fixed_8_1_AP_TRN_AP_SAT_0_8_Slice_ap_uint_1_1_Recast_Binary_24_64_BinaryWeights_3_16_36_ThresholdsActivation_4_16_1_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_uint_1_0_std_less_ap_fixed_24_16_AP_TRN_AP_WRAP_0_ap_resource_lut_s</contextNormFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>E:\Tai_lieu\DATN\vitis\hw</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>../convlayer.h</first>
											<second>ConvLayer_Batch&amp;lt;3, 3, 32, 64, 30, 3, 16, Slice&amp;lt;ap_fixed&amp;lt;8, 1, AP_TRN, AP_SAT, 0&amp;gt;, 8&amp;gt;, Slice&amp;lt;ap_uint&amp;lt;1&amp;gt;, 1&amp;gt;, Recast&amp;lt;Binary&amp;gt;, 24, 64, BinaryWeights&amp;lt;3, 16, 36&amp;gt;, ThresholdsActivation&amp;lt;4, 16, 1, ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt;, ap_uint&amp;lt;1&amp;gt;, 0, std::less&amp;lt;ap_fixed&amp;lt;24, 16, AP_TRN, AP_WRAP, 0&amp;gt; &amp;gt; &amp;gt;, ap_resource_lut&amp;gt;</second>
										</first>
										<second>118</second>
									</item>
									<item>
										<first>
											<first>../top.cpp</first>
											<second>DoCompute</second>
										</first>
										<second>129</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1109404710</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>19</item>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>5</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_7">
				<Value>
					<Obj>
						<type>2</type>
						<id>12</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1953853549</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>900</content>
			</item>
			<item class_id_reference="16" object_id="_8">
				<Value>
					<Obj>
						<type>2</type>
						<id>14</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<contextNormFuncName></contextNormFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<control></control>
						<opType></opType>
						<implIndex></implIndex>
						<coreName></coreName>
						<isStorage>0</isStorage>
						<storageDepth>0</storageDepth>
						<coreId>1953853549</coreId>
						<rtlModuleName></rtlModuleName>
					</Obj>
					<bitwidth>60</bitwidth>
				</Value>
				<const_type>5</const_type>
				<content>&lt;undef&gt;</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>1</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_9">
				<Obj>
					<type>3</type>
					<id>7</id>
					<name>DoCompute_Block_entry5993_proc</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<contextNormFuncName></contextNormFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<control></control>
					<opType></opType>
					<implIndex></implIndex>
					<coreName></coreName>
					<isStorage>0</isStorage>
					<storageDepth>0</storageDepth>
					<coreId>4294967292</coreId>
					<rtlModuleName></rtlModuleName>
				</Obj>
				<node_objs>
					<count>5</count>
					<item_version>0</item_version>
					<item>2</item>
					<item>3</item>
					<item>4</item>
					<item>5</item>
					<item>6</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>8</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_10">
				<id>10</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>2</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_11">
				<id>11</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>3</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_12">
				<id>13</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>3</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_13">
				<id>15</id>
				<edge_type>1</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>4</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_14">
				<id>16</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>4</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_15">
				<id>17</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>5</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_16">
				<id>18</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>5</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_17">
				<id>19</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>6</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_18">
			<mId>1</mId>
			<mTag>DoCompute_Block_entry5993_proc</mTag>
			<mNormTag>DoCompute_Block_entry5993_proc</mNormTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>7</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>2</mMinLatency>
			<mMaxLatency>2</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="24" tracking_level="1" version="0" object_id="_19">
		<states class_id="25" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="26" tracking_level="1" version="0" object_id="_20">
				<id>1</id>
				<operations class_id="27" tracking_level="0" version="0">
					<count>1</count>
					<item_version>0</item_version>
					<item class_id="28" tracking_level="1" version="0" object_id="_21">
						<id>2</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
				</operations>
			</item>
			<item class_id_reference="26" object_id="_22">
				<id>2</id>
				<operations>
					<count>1</count>
					<item_version>0</item_version>
					<item class_id_reference="28" object_id="_23">
						<id>3</id>
						<stage>2</stage>
						<latency>2</latency>
					</item>
				</operations>
			</item>
			<item class_id_reference="26" object_id="_24">
				<id>3</id>
				<operations>
					<count>4</count>
					<item_version>0</item_version>
					<item class_id_reference="28" object_id="_25">
						<id>3</id>
						<stage>1</stage>
						<latency>2</latency>
					</item>
					<item class_id_reference="28" object_id="_26">
						<id>4</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_27">
						<id>5</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
					<item class_id_reference="28" object_id="_28">
						<id>6</id>
						<stage>1</stage>
						<latency>1</latency>
					</item>
				</operations>
			</item>
		</states>
		<transitions class_id="29" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="30" tracking_level="1" version="0" object_id="_29">
				<inState>1</inState>
				<outState>2</outState>
				<condition class_id="31" tracking_level="0" version="0">
					<id>-1</id>
					<sop class_id="32" tracking_level="0" version="0">
						<count>1</count>
						<item_version>0</item_version>
						<item class_id="33" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</item>
					</sop>
				</condition>
			</item>
			<item class_id_reference="30" object_id="_30">
				<inState>2</inState>
				<outState>3</outState>
				<condition>
					<id>-1</id>
					<sop>
						<count>1</count>
						<item_version>0</item_version>
						<item>
							<count>0</count>
							<item_version>0</item_version>
						</item>
					</sop>
				</condition>
			</item>
		</transitions>
	</fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="35" tracking_level="0" version="0">
		<count>5</count>
		<item_version>0</item_version>
		<item class_id="36" tracking_level="0" version="0">
			<first>2</first>
			<second class_id="37" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>3</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>4</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>5</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>6</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="38" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="39" tracking_level="0" version="0">
			<first>7</first>
			<second class_id="40" tracking_level="0" version="0">
				<first>0</first>
				<second>2</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="41" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</regions>
	<dp_fu_nodes class_id="42" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="43" tracking_level="0" version="0">
			<first>8</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>2</item>
			</second>
		</item>
		<item>
			<first>14</first>
			<second>
				<count>2</count>
				<item_version>0</item_version>
				<item>3</item>
				<item>3</item>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>4</item>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>5</item>
			</second>
		</item>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="45" tracking_level="0" version="0">
		<count>2</count>
		<item_version>0</item_version>
		<item class_id="46" tracking_level="0" version="0">
			<first>mrv_1_i_fu_24</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>5</item>
			</second>
		</item>
		<item>
			<first>mrv_i_fu_19</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>4</item>
			</second>
		</item>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>1</count>
		<item_version>0</item_version>
		<item>
			<first>grp_fu_14</first>
			<second>
				<count>2</count>
				<item_version>0</item_version>
				<item>3</item>
				<item>3</item>
			</second>
		</item>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>1</count>
		<item_version>0</item_version>
		<item>
			<first>numReps_read_read_fu_8</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>2</item>
			</second>
		</item>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="47" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>1</count>
		<item_version>0</item_version>
		<item>
			<first>30</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>2</item>
			</second>
		</item>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>1</count>
		<item_version>0</item_version>
		<item>
			<first>numReps_read_reg_30</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>2</item>
			</second>
		</item>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="48" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="49" tracking_level="0" version="0">
			<first>numReps</first>
			<second>
				<count>1</count>
				<item_version>0</item_version>
				<item>
					<first>read</first>
					<second>
						<count>1</count>
						<item_version>0</item_version>
						<item>2</item>
					</second>
				</item>
			</second>
		</item>
	</dp_port_io_nodes>
	<port2core>
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>2</count>
		<item_version>0</item_version>
		<item>
			<first>2</first>
			<second>
				<first>666</first>
				<second>10</second>
			</second>
		</item>
		<item>
			<first>3</first>
			<second>
				<first>12</first>
				<second>0</second>
			</second>
		</item>
	</node2core>
</syndb>
</boost_serialization>

