-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    wa_in_i1518_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    wa_in_i1518_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    wa_in_i1518_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    wa_in_i1518_empty_n : IN STD_LOGIC;
    wa_in_i1518_read : OUT STD_LOGIC;
    convInp_i17_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    convInp_i17_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    convInp_i17_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    convInp_i17_full_n : IN STD_LOGIC;
    convInp_i17_write : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (43 downto 0) );
end;


architecture behav of BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv44_0 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv44_1 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000001";
    constant ap_const_lv12_EA0 : STD_LOGIC_VECTOR (11 downto 0) := "111010100000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_167 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln107_reg_970 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_reg_1015 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op175_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal icmp_ln107_reg_970_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_974 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_974_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op203_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln104_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal wa_in_i1518_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal convInp_i17_blk_n : STD_LOGIC;
    signal reg_323 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln104_reg_957 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln105_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln105_reg_961 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln98_fu_462_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln98_reg_966 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln123_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln124_1_fu_500_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln124_1_reg_978 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_807_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_reg_1025 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal inputBuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_ce0 : STD_LOGIC;
    signal inputBuf_we0 : STD_LOGIC;
    signal inputBuf_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_ce1 : STD_LOGIC;
    signal inputBuf_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_1_ce0 : STD_LOGIC;
    signal inputBuf_1_we0 : STD_LOGIC;
    signal inputBuf_1_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_1_ce1 : STD_LOGIC;
    signal inputBuf_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_2_ce0 : STD_LOGIC;
    signal inputBuf_2_we0 : STD_LOGIC;
    signal inputBuf_2_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_2_ce1 : STD_LOGIC;
    signal inputBuf_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_3_ce0 : STD_LOGIC;
    signal inputBuf_3_we0 : STD_LOGIC;
    signal inputBuf_3_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_3_ce1 : STD_LOGIC;
    signal inputBuf_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln129_fu_534_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_fu_830_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln110_fu_838_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_block_1_fu_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln98_fu_450_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_299_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_011_fu_78 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal i_fu_416_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal indvar_flatten_fu_82 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000000";
    signal add_ln104_fu_398_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal ofm_y_fu_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ofm_y_2_fu_660_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln132_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_x_fu_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ofm_x_1_fu_605_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_1_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal inp_3_fu_652_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_fu_766_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal k_y_1_fu_490_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal k_x_1_fu_559_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_1_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_315_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal count_simd_1_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_1_fu_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_287_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_block_fu_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal counter_internal_block_3_fu_753_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_304_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_fu_410_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln124_fu_496_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln128_1_fu_510_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln128_fu_506_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln128_fu_514_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln_fu_520_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln105_fu_458_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal current_line_in_block_fu_528_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ofm_y_1_fu_640_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln144_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_1_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal counter_internal_block_2_fu_741_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln172_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_fu_807_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op81_load_state3 : BOOLEAN;
    signal ap_enable_operation_81 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op170_load_state4 : BOOLEAN;
    signal ap_enable_operation_170 : BOOLEAN;
    signal ap_enable_state4_pp0_iter3_stage0 : BOOLEAN;
    signal ap_predicate_op185_store_state4 : BOOLEAN;
    signal ap_enable_operation_185 : BOOLEAN;
    signal ap_predicate_op199_store_state4 : BOOLEAN;
    signal ap_enable_operation_199 : BOOLEAN;
    signal ap_predicate_op82_load_state3 : BOOLEAN;
    signal ap_enable_operation_82 : BOOLEAN;
    signal ap_predicate_op171_load_state4 : BOOLEAN;
    signal ap_enable_operation_171 : BOOLEAN;
    signal ap_predicate_op183_store_state4 : BOOLEAN;
    signal ap_enable_operation_183 : BOOLEAN;
    signal ap_predicate_op197_store_state4 : BOOLEAN;
    signal ap_enable_operation_197 : BOOLEAN;
    signal ap_predicate_op83_load_state3 : BOOLEAN;
    signal ap_enable_operation_83 : BOOLEAN;
    signal ap_predicate_op172_load_state4 : BOOLEAN;
    signal ap_enable_operation_172 : BOOLEAN;
    signal ap_predicate_op181_store_state4 : BOOLEAN;
    signal ap_enable_operation_181 : BOOLEAN;
    signal ap_predicate_op195_store_state4 : BOOLEAN;
    signal ap_enable_operation_195 : BOOLEAN;
    signal ap_predicate_op84_load_state3 : BOOLEAN;
    signal ap_enable_operation_84 : BOOLEAN;
    signal ap_predicate_op173_load_state4 : BOOLEAN;
    signal ap_enable_operation_173 : BOOLEAN;
    signal ap_predicate_op187_store_state4 : BOOLEAN;
    signal ap_enable_operation_187 : BOOLEAN;
    signal ap_predicate_op201_store_state4 : BOOLEAN;
    signal ap_enable_operation_201 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_729 : BOOLEAN;
    signal ap_condition_733 : BOOLEAN;
    signal ap_condition_736 : BOOLEAN;
    signal ap_condition_739 : BOOLEAN;
    signal ap_condition_742 : BOOLEAN;
    signal ap_condition_745 : BOOLEAN;
    signal p_0_fu_807_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_807_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_807_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_fu_807_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component BlackBoxJam_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5_inputBncg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component BlackBoxJam_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    inputBuf_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5_inputBncg
    generic map (
        DataWidth => 32,
        AddressRange => 48,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_address0,
        ce0 => inputBuf_ce0,
        we0 => inputBuf_we0,
        d0 => wa_in_i1518_dout,
        address1 => inputBuf_address1,
        ce1 => inputBuf_ce1,
        q1 => inputBuf_q1);

    inputBuf_1_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5_inputBncg
    generic map (
        DataWidth => 32,
        AddressRange => 48,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_address0,
        ce0 => inputBuf_1_ce0,
        we0 => inputBuf_1_we0,
        d0 => wa_in_i1518_dout,
        address1 => inputBuf_1_address1,
        ce1 => inputBuf_1_ce1,
        q1 => inputBuf_1_q1);

    inputBuf_2_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5_inputBncg
    generic map (
        DataWidth => 32,
        AddressRange => 48,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_address0,
        ce0 => inputBuf_2_ce0,
        we0 => inputBuf_2_we0,
        d0 => wa_in_i1518_dout,
        address1 => inputBuf_2_address1,
        ce1 => inputBuf_2_ce1,
        q1 => inputBuf_2_q1);

    inputBuf_3_U : component BlackBoxJam_ConvolutionInputGenerator_Pipeline_VITIS_LOOP_104_1_VITIS_LOOP_105_2_5_inputBncg
    generic map (
        DataWidth => 32,
        AddressRange => 48,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_address0,
        ce0 => inputBuf_3_ce0,
        we0 => inputBuf_3_we0,
        d0 => wa_in_i1518_dout,
        address1 => inputBuf_3_address1,
        ce1 => inputBuf_3_ce1,
        q1 => inputBuf_3_q1);

    sparsemux_9_2_32_1_1_U406 : component BlackBoxJam_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => inputBuf_q1,
        din1 => inputBuf_1_q1,
        din2 => inputBuf_2_q1,
        din3 => inputBuf_3_q1,
        def => p_0_fu_807_p9,
        sel => add_ln124_1_reg_978,
        dout => p_0_fu_807_p11);

    flow_control_loop_pipe_sequential_init_U : component BlackBoxJam_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    count_simd_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_fu_565_p2 = ap_const_lv1_0) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_581_p2 = ap_const_lv1_0) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_611_p2 = ap_const_lv1_0) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 
    = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_611_p2 = ap_const_lv1_1) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                count_simd_fu_110 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln132_fu_548_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0))) then 
                count_simd_fu_110 <= count_simd_1_fu_542_p2;
            end if; 
        end if;
    end process;

    counter_internal_block_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then 
                counter_internal_block_fu_118 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0))) then 
                counter_internal_block_fu_118 <= counter_internal_block_3_fu_753_p3;
            end if; 
        end if;
    end process;

    current_block_write_1_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                current_block_write_1_fu_106 <= ap_const_lv32_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then 
                current_block_write_1_fu_106 <= grp_fu_315_p3;
            end if; 
        end if;
    end process;

    current_line_1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then 
                current_line_1_fu_114 <= ap_const_lv32_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then 
                current_line_1_fu_114 <= grp_fu_287_p2;
            end if; 
        end if;
    end process;

    i_011_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_011_fu_78 <= ap_const_lv12_0;
                elsif (((icmp_ln104_fu_393_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_011_fu_78 <= i_fu_416_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_82 <= ap_const_lv44_0;
                elsif (((icmp_ln104_fu_393_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_82 <= add_ln104_fu_398_p2;
                end if;
            end if; 
        end if;
    end process;

    inp_1_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    inp_1_fu_94 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_733)) then 
                    inp_1_fu_94 <= inp_fu_766_p2;
                elsif ((ap_const_boolean_1 = ap_condition_729)) then 
                    inp_1_fu_94 <= inp_3_fu_652_p3;
                end if;
            end if; 
        end if;
    end process;

    k_x_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_581_p2 = ap_const_lv1_0) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_611_p2 = ap_const_lv1_0) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_611_p2 = ap_const_lv1_1) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 
    = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                k_x_fu_102 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln135_fu_565_p2 = ap_const_lv1_0) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0))) then 
                k_x_fu_102 <= k_x_1_fu_559_p2;
            end if; 
        end if;
    end process;

    k_y_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                k_y_fu_98 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln138_fu_581_p2 = ap_const_lv1_0) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0))) then 
                k_y_fu_98 <= k_y_1_fu_490_p2;
            end if; 
        end if;
    end process;

    ofm_x_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_611_p2 = ap_const_lv1_1) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ofm_x_fu_90 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln141_fu_611_p2 = ap_const_lv1_0) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0))) then 
                ofm_x_fu_90 <= ofm_x_1_fu_605_p2;
            end if; 
        end if;
    end process;

    ofm_y_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ofm_y_fu_86 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_729)) then 
                    ofm_y_fu_86 <= ofm_y_2_fu_660_p3;
                end if;
            end if; 
        end if;
    end process;

    read_block_1_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                read_block_1_fu_74 <= ap_const_lv32_0;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then 
                read_block_1_fu_74 <= grp_fu_299_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (grp_fu_293_p2 = ap_const_lv1_0) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then 
                read_block_1_fu_74 <= select_ln98_fu_450_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln124_1_reg_978 <= add_ln124_1_fu_500_p2;
                and_ln153_reg_1015 <= and_ln153_fu_705_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln107_reg_970 <= icmp_ln107_fu_466_p2;
                icmp_ln107_reg_970_pp0_iter3_reg <= icmp_ln107_reg_970;
                icmp_ln123_reg_974 <= icmp_ln123_fu_472_p2;
                icmp_ln123_reg_974_pp0_iter3_reg <= icmp_ln123_reg_974;
                p_0_reg_1025 <= p_0_fu_807_p11;
                trunc_ln98_reg_966 <= trunc_ln98_fu_462_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln104_reg_957 <= icmp_ln104_fu_393_p2;
                icmp_ln105_reg_961 <= icmp_ln105_fu_404_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_fu_705_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0)))) then
                reg_323 <= current_line_1_fu_114;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln104_fu_398_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_82) + unsigned(ap_const_lv44_1));
    add_ln105_fu_410_p2 <= std_logic_vector(unsigned(i_011_fu_78) + unsigned(ap_const_lv12_1));
    add_ln124_1_fu_500_p2 <= std_logic_vector(unsigned(trunc_ln124_fu_496_p1) + unsigned(trunc_ln98_fu_462_p1));
    add_ln128_fu_514_p2 <= std_logic_vector(unsigned(trunc_ln128_1_fu_510_p1) + unsigned(trunc_ln128_fu_506_p1));
    and_ln153_fu_705_p2 <= (icmp_ln153_fu_693_p2 and icmp_ln153_1_fu_699_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state4_pp0_stage0_iter3, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state4_pp0_stage0_iter3, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state4_pp0_stage0_iter3, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(wa_in_i1518_empty_n, icmp_ln107_reg_970, ap_predicate_op175_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (((icmp_ln107_reg_970 = ap_const_lv1_1) and (wa_in_i1518_empty_n = ap_const_logic_0)) or ((ap_predicate_op175_read_state4 = ap_const_boolean_1) and (wa_in_i1518_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(convInp_i17_full_n, ap_predicate_op203_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((ap_predicate_op203_write_state5 = ap_const_boolean_1) and (convInp_i17_full_n = ap_const_logic_0));
    end process;


    ap_condition_729_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln104_reg_957, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2, icmp_ln132_fu_548_p2, icmp_ln135_fu_565_p2, icmp_ln138_fu_581_p2, icmp_ln141_fu_611_p2)
    begin
                ap_condition_729 <= ((icmp_ln141_fu_611_p2 = ap_const_lv1_1) and (icmp_ln138_fu_581_p2 = ap_const_lv1_1) and (icmp_ln135_fu_565_p2 = ap_const_lv1_1) and (icmp_ln132_fu_548_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0));
    end process;


    ap_condition_733_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln104_reg_957, icmp_ln107_fu_466_p2)
    begin
                ap_condition_733 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_1) and (icmp_ln104_reg_957 = ap_const_lv1_0));
    end process;


    ap_condition_736_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_966)
    begin
                ap_condition_736 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_1));
    end process;


    ap_condition_739_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_966)
    begin
                ap_condition_739 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_2));
    end process;


    ap_condition_742_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_966)
    begin
                ap_condition_742 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_3));
    end process;


    ap_condition_745_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, trunc_ln98_reg_966)
    begin
                ap_condition_745 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln104_fu_393_p2)
    begin
        if (((icmp_ln104_fu_393_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln104_reg_957)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln104_reg_957 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_170_assign_proc : process(ap_predicate_op170_load_state4)
    begin
                ap_enable_operation_170 <= (ap_predicate_op170_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_171_assign_proc : process(ap_predicate_op171_load_state4)
    begin
                ap_enable_operation_171 <= (ap_predicate_op171_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_172_assign_proc : process(ap_predicate_op172_load_state4)
    begin
                ap_enable_operation_172 <= (ap_predicate_op172_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_173_assign_proc : process(ap_predicate_op173_load_state4)
    begin
                ap_enable_operation_173 <= (ap_predicate_op173_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_181_assign_proc : process(ap_predicate_op181_store_state4)
    begin
                ap_enable_operation_181 <= (ap_predicate_op181_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_183_assign_proc : process(ap_predicate_op183_store_state4)
    begin
                ap_enable_operation_183 <= (ap_predicate_op183_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_185_assign_proc : process(ap_predicate_op185_store_state4)
    begin
                ap_enable_operation_185 <= (ap_predicate_op185_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_187_assign_proc : process(ap_predicate_op187_store_state4)
    begin
                ap_enable_operation_187 <= (ap_predicate_op187_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_195_assign_proc : process(ap_predicate_op195_store_state4)
    begin
                ap_enable_operation_195 <= (ap_predicate_op195_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_197_assign_proc : process(ap_predicate_op197_store_state4)
    begin
                ap_enable_operation_197 <= (ap_predicate_op197_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_199_assign_proc : process(ap_predicate_op199_store_state4)
    begin
                ap_enable_operation_199 <= (ap_predicate_op199_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_201_assign_proc : process(ap_predicate_op201_store_state4)
    begin
                ap_enable_operation_201 <= (ap_predicate_op201_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_81_assign_proc : process(ap_predicate_op81_load_state3)
    begin
                ap_enable_operation_81 <= (ap_predicate_op81_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_82_assign_proc : process(ap_predicate_op82_load_state3)
    begin
                ap_enable_operation_82 <= (ap_predicate_op82_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_83_assign_proc : process(ap_predicate_op83_load_state3)
    begin
                ap_enable_operation_83 <= (ap_predicate_op83_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_84_assign_proc : process(ap_predicate_op84_load_state3)
    begin
                ap_enable_operation_84 <= (ap_predicate_op84_load_state3 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state4_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_predicate_op170_load_state4_assign_proc : process(icmp_ln107_reg_970, icmp_ln123_reg_974)
    begin
                ap_predicate_op170_load_state4 <= ((icmp_ln123_reg_974 = ap_const_lv1_1) and (icmp_ln107_reg_970 = ap_const_lv1_0));
    end process;


    ap_predicate_op171_load_state4_assign_proc : process(icmp_ln107_reg_970, icmp_ln123_reg_974)
    begin
                ap_predicate_op171_load_state4 <= ((icmp_ln123_reg_974 = ap_const_lv1_1) and (icmp_ln107_reg_970 = ap_const_lv1_0));
    end process;


    ap_predicate_op172_load_state4_assign_proc : process(icmp_ln107_reg_970, icmp_ln123_reg_974)
    begin
                ap_predicate_op172_load_state4 <= ((icmp_ln123_reg_974 = ap_const_lv1_1) and (icmp_ln107_reg_970 = ap_const_lv1_0));
    end process;


    ap_predicate_op173_load_state4_assign_proc : process(icmp_ln107_reg_970, icmp_ln123_reg_974)
    begin
                ap_predicate_op173_load_state4 <= ((icmp_ln123_reg_974 = ap_const_lv1_1) and (icmp_ln107_reg_970 = ap_const_lv1_0));
    end process;


    ap_predicate_op175_read_state4_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015)
    begin
                ap_predicate_op175_read_state4 <= ((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0));
    end process;


    ap_predicate_op181_store_state4_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, trunc_ln98_reg_966)
    begin
                ap_predicate_op181_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (trunc_ln98_reg_966 = ap_const_lv2_2));
    end process;


    ap_predicate_op183_store_state4_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, trunc_ln98_reg_966)
    begin
                ap_predicate_op183_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (trunc_ln98_reg_966 = ap_const_lv2_1));
    end process;


    ap_predicate_op185_store_state4_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, trunc_ln98_reg_966)
    begin
                ap_predicate_op185_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (trunc_ln98_reg_966 = ap_const_lv2_0));
    end process;


    ap_predicate_op187_store_state4_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, trunc_ln98_reg_966)
    begin
                ap_predicate_op187_store_state4 <= ((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (trunc_ln98_reg_966 = ap_const_lv2_3));
    end process;


    ap_predicate_op195_store_state4_assign_proc : process(icmp_ln107_reg_970, trunc_ln98_reg_966)
    begin
                ap_predicate_op195_store_state4 <= ((icmp_ln107_reg_970 = ap_const_lv1_1) and (trunc_ln98_reg_966 = ap_const_lv2_2));
    end process;


    ap_predicate_op197_store_state4_assign_proc : process(icmp_ln107_reg_970, trunc_ln98_reg_966)
    begin
                ap_predicate_op197_store_state4 <= ((icmp_ln107_reg_970 = ap_const_lv1_1) and (trunc_ln98_reg_966 = ap_const_lv2_1));
    end process;


    ap_predicate_op199_store_state4_assign_proc : process(icmp_ln107_reg_970, trunc_ln98_reg_966)
    begin
                ap_predicate_op199_store_state4 <= ((icmp_ln107_reg_970 = ap_const_lv1_1) and (trunc_ln98_reg_966 = ap_const_lv2_0));
    end process;


    ap_predicate_op201_store_state4_assign_proc : process(icmp_ln107_reg_970, trunc_ln98_reg_966)
    begin
                ap_predicate_op201_store_state4 <= ((icmp_ln107_reg_970 = ap_const_lv1_1) and (trunc_ln98_reg_966 = ap_const_lv2_3));
    end process;


    ap_predicate_op203_write_state5_assign_proc : process(icmp_ln107_reg_970_pp0_iter3_reg, icmp_ln123_reg_974_pp0_iter3_reg)
    begin
                ap_predicate_op203_write_state5 <= ((icmp_ln123_reg_974_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln107_reg_970_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op81_load_state3_assign_proc : process(icmp_ln104_reg_957, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op81_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0));
    end process;


    ap_predicate_op82_load_state3_assign_proc : process(icmp_ln104_reg_957, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op82_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0));
    end process;


    ap_predicate_op83_load_state3_assign_proc : process(icmp_ln104_reg_957, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op83_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0));
    end process;


    ap_predicate_op84_load_state3_assign_proc : process(icmp_ln104_reg_957, icmp_ln107_fu_466_p2, icmp_ln123_fu_472_p2)
    begin
                ap_predicate_op84_load_state3 <= ((icmp_ln123_fu_472_p2 = ap_const_lv1_1) and (icmp_ln107_fu_466_p2 = ap_const_lv1_0) and (icmp_ln104_reg_957 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    convInp_i17_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, convInp_i17_full_n, ap_predicate_op203_write_state5, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op203_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            convInp_i17_blk_n <= convInp_i17_full_n;
        else 
            convInp_i17_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    convInp_i17_din <= p_0_reg_1025;

    convInp_i17_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op203_write_state5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op203_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            convInp_i17_write <= ap_const_logic_1;
        else 
            convInp_i17_write <= ap_const_logic_0;
        end if; 
    end process;

    count_simd_1_fu_542_p2 <= std_logic_vector(unsigned(count_simd_fu_110) + unsigned(ap_const_lv32_1));
    counter_internal_block_2_fu_741_p2 <= std_logic_vector(unsigned(counter_internal_block_fu_118) + unsigned(ap_const_lv32_1));
    counter_internal_block_3_fu_753_p3 <= 
        ap_const_lv32_0 when (icmp_ln172_fu_747_p2(0) = '1') else 
        counter_internal_block_2_fu_741_p2;
    current_line_in_block_fu_528_p2 <= std_logic_vector(unsigned(shl_ln_fu_520_p3) + unsigned(trunc_ln105_fu_458_p1));
    grp_fu_287_p2 <= std_logic_vector(unsigned(current_line_1_fu_114) + unsigned(ap_const_lv32_1));
    grp_fu_293_p2 <= "1" when (grp_fu_287_p2 = ap_const_lv32_30) else "0";
    grp_fu_299_p2 <= std_logic_vector(unsigned(select_ln98_fu_450_p3) + unsigned(ap_const_lv32_1));
    grp_fu_304_p2 <= std_logic_vector(unsigned(current_block_write_1_fu_106) + unsigned(ap_const_lv32_1));
    grp_fu_309_p2 <= "1" when (grp_fu_304_p2 = ap_const_lv32_4) else "0";
    grp_fu_315_p3 <= 
        ap_const_lv32_0 when (grp_fu_309_p2(0) = '1') else 
        grp_fu_304_p2;
    i_fu_416_p3 <= 
        ap_const_lv12_1 when (icmp_ln105_fu_404_p2(0) = '1') else 
        add_ln105_fu_410_p2;
    icmp_ln104_fu_393_p2 <= "1" when (indvar_flatten_fu_82 = bound) else "0";
    icmp_ln105_fu_404_p2 <= "1" when (i_011_fu_78 = ap_const_lv12_EA0) else "0";
    icmp_ln107_fu_466_p2 <= "1" when (unsigned(inp_1_fu_94) < unsigned(ap_const_lv32_90)) else "0";
    icmp_ln123_fu_472_p2 <= "1" when (unsigned(counter_internal_block_fu_118) < unsigned(ap_const_lv32_167)) else "0";
    icmp_ln132_fu_548_p2 <= "1" when (count_simd_1_fu_542_p2 = ap_const_lv32_4) else "0";
    icmp_ln135_fu_565_p2 <= "1" when (k_x_1_fu_559_p2 = ap_const_lv32_3) else "0";
    icmp_ln138_fu_581_p2 <= "1" when (k_y_1_fu_490_p2 = ap_const_lv32_3) else "0";
    icmp_ln141_fu_611_p2 <= "1" when (ofm_x_1_fu_605_p2 = ap_const_lv32_A) else "0";
    icmp_ln144_fu_646_p2 <= "1" when (ofm_y_1_fu_640_p2 = ap_const_lv32_A) else "0";
    icmp_ln153_1_fu_699_p2 <= "1" when (unsigned(select_ln98_fu_450_p3) < unsigned(ap_const_lv32_C)) else "0";
    icmp_ln153_fu_693_p2 <= "1" when (unsigned(counter_internal_block_fu_118) < unsigned(ap_const_lv32_2F)) else "0";
    icmp_ln172_fu_747_p2 <= "1" when (counter_internal_block_2_fu_741_p2 = ap_const_lv32_167) else "0";
    inp_3_fu_652_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_646_p2(0) = '1') else 
        inp_1_fu_94;
    inp_fu_766_p2 <= std_logic_vector(unsigned(inp_1_fu_94) + unsigned(ap_const_lv32_1));

    inputBuf_1_address0_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, zext_ln156_fu_830_p1, zext_ln110_fu_838_p1, ap_condition_736)
    begin
        if ((ap_const_boolean_1 = ap_condition_736)) then
            if ((icmp_ln107_reg_970 = ap_const_lv1_1)) then 
                inputBuf_1_address0 <= zext_ln110_fu_838_p1(6 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0))) then 
                inputBuf_1_address0 <= zext_ln156_fu_830_p1(6 - 1 downto 0);
            else 
                inputBuf_1_address0 <= "XXXXXX";
            end if;
        else 
            inputBuf_1_address0 <= "XXXXXX";
        end if; 
    end process;

    inputBuf_1_address1 <= zext_ln129_fu_534_p1(6 - 1 downto 0);

    inputBuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_1)))) then 
            inputBuf_1_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_1_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_1)))) then 
            inputBuf_1_we0 <= ap_const_logic_1;
        else 
            inputBuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_address0_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, zext_ln156_fu_830_p1, zext_ln110_fu_838_p1, ap_condition_739)
    begin
        if ((ap_const_boolean_1 = ap_condition_739)) then
            if ((icmp_ln107_reg_970 = ap_const_lv1_1)) then 
                inputBuf_2_address0 <= zext_ln110_fu_838_p1(6 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0))) then 
                inputBuf_2_address0 <= zext_ln156_fu_830_p1(6 - 1 downto 0);
            else 
                inputBuf_2_address0 <= "XXXXXX";
            end if;
        else 
            inputBuf_2_address0 <= "XXXXXX";
        end if; 
    end process;

    inputBuf_2_address1 <= zext_ln129_fu_534_p1(6 - 1 downto 0);

    inputBuf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_2)))) then 
            inputBuf_2_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_2_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_2)))) then 
            inputBuf_2_we0 <= ap_const_logic_1;
        else 
            inputBuf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_address0_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, zext_ln156_fu_830_p1, zext_ln110_fu_838_p1, ap_condition_742)
    begin
        if ((ap_const_boolean_1 = ap_condition_742)) then
            if ((icmp_ln107_reg_970 = ap_const_lv1_1)) then 
                inputBuf_3_address0 <= zext_ln110_fu_838_p1(6 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0))) then 
                inputBuf_3_address0 <= zext_ln156_fu_830_p1(6 - 1 downto 0);
            else 
                inputBuf_3_address0 <= "XXXXXX";
            end if;
        else 
            inputBuf_3_address0 <= "XXXXXX";
        end if; 
    end process;

    inputBuf_3_address1 <= zext_ln129_fu_534_p1(6 - 1 downto 0);

    inputBuf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_3)))) then 
            inputBuf_3_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_3_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_3)))) then 
            inputBuf_3_we0 <= ap_const_logic_1;
        else 
            inputBuf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_address0_assign_proc : process(icmp_ln107_reg_970, and_ln153_reg_1015, zext_ln156_fu_830_p1, zext_ln110_fu_838_p1, ap_condition_745)
    begin
        if ((ap_const_boolean_1 = ap_condition_745)) then
            if ((icmp_ln107_reg_970 = ap_const_lv1_1)) then 
                inputBuf_address0 <= zext_ln110_fu_838_p1(6 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0))) then 
                inputBuf_address0 <= zext_ln156_fu_830_p1(6 - 1 downto 0);
            else 
                inputBuf_address0 <= "XXXXXX";
            end if;
        else 
            inputBuf_address0 <= "XXXXXX";
        end if; 
    end process;

    inputBuf_address1 <= zext_ln129_fu_534_p1(6 - 1 downto 0);

    inputBuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_0)))) then 
            inputBuf_ce0 <= ap_const_logic_1;
        else 
            inputBuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            inputBuf_ce1 <= ap_const_logic_1;
        else 
            inputBuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_we0_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, and_ln153_reg_1015, ap_block_pp0_stage0_11001, trunc_ln98_reg_966)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln153_reg_1015) and (icmp_ln107_reg_970 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (trunc_ln98_reg_966 = ap_const_lv2_0)))) then 
            inputBuf_we0 <= ap_const_logic_1;
        else 
            inputBuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    k_x_1_fu_559_p2 <= std_logic_vector(unsigned(k_x_fu_102) + unsigned(ap_const_lv32_1));
    k_y_1_fu_490_p2 <= std_logic_vector(unsigned(k_y_fu_98) + unsigned(ap_const_lv32_1));
    ofm_x_1_fu_605_p2 <= std_logic_vector(unsigned(ofm_x_fu_90) + unsigned(ap_const_lv32_1));
    ofm_y_1_fu_640_p2 <= std_logic_vector(unsigned(ofm_y_fu_86) + unsigned(ap_const_lv32_1));
    ofm_y_2_fu_660_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_646_p2(0) = '1') else 
        ofm_y_1_fu_640_p2;
    p_0_fu_807_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln98_fu_450_p3 <= 
        ap_const_lv32_0 when (icmp_ln105_reg_961(0) = '1') else 
        read_block_1_fu_74;
    shl_ln_fu_520_p3 <= (add_ln128_fu_514_p2 & ap_const_lv2_0);
    trunc_ln105_fu_458_p1 <= count_simd_fu_110(6 - 1 downto 0);
    trunc_ln124_fu_496_p1 <= k_y_1_fu_490_p2(2 - 1 downto 0);
    trunc_ln128_1_fu_510_p1 <= ofm_x_fu_90(4 - 1 downto 0);
    trunc_ln128_fu_506_p1 <= k_x_fu_102(4 - 1 downto 0);
    trunc_ln98_fu_462_p1 <= current_block_write_1_fu_106(2 - 1 downto 0);

    wa_in_i1518_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, wa_in_i1518_empty_n, icmp_ln107_reg_970, ap_predicate_op175_read_state4, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op175_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            wa_in_i1518_blk_n <= wa_in_i1518_empty_n;
        else 
            wa_in_i1518_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    wa_in_i1518_read_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln107_reg_970, ap_predicate_op175_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_reg_970 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op175_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            wa_in_i1518_read <= ap_const_logic_1;
        else 
            wa_in_i1518_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln110_fu_838_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_323),64));
    zext_ln129_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_in_block_fu_528_p2),64));
    zext_ln156_fu_830_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_323),64));
end behav;
