-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BlackBoxJam_Matrix_Vector_Activate_Batch_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    convInp_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    convInp_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    convInp_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    convInp_1_empty_n : IN STD_LOGIC;
    convInp_1_read : OUT STD_LOGIC;
    mvOut_m_buffer_6_din : OUT STD_LOGIC_VECTOR (3 downto 0);
    mvOut_m_buffer_6_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    mvOut_m_buffer_6_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    mvOut_m_buffer_6_full_n : IN STD_LOGIC;
    mvOut_m_buffer_6_write : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZL8weights4_0_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZL8weights4_0_ce0 : OUT STD_LOGIC;
    p_ZL8weights4_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL8weights4_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZL8weights4_1_ce0 : OUT STD_LOGIC;
    p_ZL8weights4_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL8weights4_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZL8weights4_2_ce0 : OUT STD_LOGIC;
    p_ZL8weights4_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL8weights4_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    p_ZL8weights4_3_ce0 : OUT STD_LOGIC;
    p_ZL8weights4_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZL8threshs4_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_ZL8threshs4_0_ce0 : OUT STD_LOGIC;
    p_ZL8threshs4_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL8threshs4_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_ZL8threshs4_1_ce0 : OUT STD_LOGIC;
    p_ZL8threshs4_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL8threshs4_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_ZL8threshs4_2_ce0 : OUT STD_LOGIC;
    p_ZL8threshs4_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL8threshs4_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_ZL8threshs4_3_ce0 : OUT STD_LOGIC;
    p_ZL8threshs4_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of BlackBoxJam_Matrix_Vector_Activate_Batch_7 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal mul_i_fu_97_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_103 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_idle : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_ready : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_convInp_1_read : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_din : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_write : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_0_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_0_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_1_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_2_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_2_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_3_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_3_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_0_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_1_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_2_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_3_ce0 : STD_LOGIC;
    signal grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal empty_fu_77_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_shl_i_fu_81_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl1_i_fu_89_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component BlackBoxJam_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        convInp_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        convInp_1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        convInp_1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        convInp_1_empty_n : IN STD_LOGIC;
        convInp_1_read : OUT STD_LOGIC;
        mvOut_m_buffer_6_din : OUT STD_LOGIC_VECTOR (3 downto 0);
        mvOut_m_buffer_6_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mvOut_m_buffer_6_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mvOut_m_buffer_6_full_n : IN STD_LOGIC;
        mvOut_m_buffer_6_write : OUT STD_LOGIC;
        mul_i : IN STD_LOGIC_VECTOR (31 downto 0);
        p_ZL8weights4_0_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_ZL8weights4_0_ce0 : OUT STD_LOGIC;
        p_ZL8weights4_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_ZL8weights4_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_ZL8weights4_1_ce0 : OUT STD_LOGIC;
        p_ZL8weights4_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_ZL8weights4_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_ZL8weights4_2_ce0 : OUT STD_LOGIC;
        p_ZL8weights4_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_ZL8weights4_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        p_ZL8weights4_3_ce0 : OUT STD_LOGIC;
        p_ZL8weights4_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_ZL8threshs4_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZL8threshs4_0_ce0 : OUT STD_LOGIC;
        p_ZL8threshs4_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL8threshs4_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZL8threshs4_1_ce0 : OUT STD_LOGIC;
        p_ZL8threshs4_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL8threshs4_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZL8threshs4_2_ce0 : OUT STD_LOGIC;
        p_ZL8threshs4_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZL8threshs4_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_ZL8threshs4_3_ce0 : OUT STD_LOGIC;
        p_ZL8threshs4_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52 : component BlackBoxJam_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start,
        ap_done => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done,
        ap_idle => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_idle,
        ap_ready => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_ready,
        convInp_1_dout => convInp_1_dout,
        convInp_1_num_data_valid => ap_const_lv3_0,
        convInp_1_fifo_cap => ap_const_lv3_0,
        convInp_1_empty_n => convInp_1_empty_n,
        convInp_1_read => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_convInp_1_read,
        mvOut_m_buffer_6_din => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_din,
        mvOut_m_buffer_6_num_data_valid => ap_const_lv3_0,
        mvOut_m_buffer_6_fifo_cap => ap_const_lv3_0,
        mvOut_m_buffer_6_full_n => mvOut_m_buffer_6_full_n,
        mvOut_m_buffer_6_write => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_write,
        mul_i => mul_i_reg_103,
        p_ZL8weights4_0_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_0_address0,
        p_ZL8weights4_0_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_0_ce0,
        p_ZL8weights4_0_q0 => p_ZL8weights4_0_q0,
        p_ZL8weights4_1_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_1_address0,
        p_ZL8weights4_1_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_1_ce0,
        p_ZL8weights4_1_q0 => p_ZL8weights4_1_q0,
        p_ZL8weights4_2_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_2_address0,
        p_ZL8weights4_2_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_2_ce0,
        p_ZL8weights4_2_q0 => p_ZL8weights4_2_q0,
        p_ZL8weights4_3_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_3_address0,
        p_ZL8weights4_3_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_3_ce0,
        p_ZL8weights4_3_q0 => p_ZL8weights4_3_q0,
        p_ZL8threshs4_0_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_0_address0,
        p_ZL8threshs4_0_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_0_ce0,
        p_ZL8threshs4_0_q0 => p_ZL8threshs4_0_q0,
        p_ZL8threshs4_1_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_1_address0,
        p_ZL8threshs4_1_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_1_ce0,
        p_ZL8threshs4_1_q0 => p_ZL8threshs4_1_q0,
        p_ZL8threshs4_2_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_2_address0,
        p_ZL8threshs4_2_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_2_ce0,
        p_ZL8threshs4_2_q0 => p_ZL8threshs4_2_q0,
        p_ZL8threshs4_3_address0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_3_address0,
        p_ZL8threshs4_3_ce0 => grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_3_ce0,
        p_ZL8threshs4_3_q0 => p_ZL8threshs4_3_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_ready = ap_const_logic_1)) then 
                    grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    mul_i_reg_103(31 downto 8) <= mul_i_fu_97_p2(31 downto 8);
            end if;
        end if;
    end process;
    mul_i_reg_103(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done)
    begin
        if ((grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    convInp_1_read_assign_proc : process(grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_convInp_1_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            convInp_1_read <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_convInp_1_read;
        else 
            convInp_1_read <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_77_p1 <= p_read(21 - 1 downto 0);
    grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_start_reg;

    internal_ap_ready_assign_proc : process(grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    mul_i_fu_97_p2 <= std_logic_vector(unsigned(p_shl_i_fu_81_p3) + unsigned(p_shl1_i_fu_89_p3));
    mvOut_m_buffer_6_din <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_din;

    mvOut_m_buffer_6_write_assign_proc : process(grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mvOut_m_buffer_6_write <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_mvOut_m_buffer_6_write;
        else 
            mvOut_m_buffer_6_write <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL8threshs4_0_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_0_address0;
    p_ZL8threshs4_0_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_0_ce0;
    p_ZL8threshs4_1_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_1_address0;
    p_ZL8threshs4_1_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_1_ce0;
    p_ZL8threshs4_2_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_2_address0;
    p_ZL8threshs4_2_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_2_ce0;
    p_ZL8threshs4_3_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_3_address0;
    p_ZL8threshs4_3_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8threshs4_3_ce0;
    p_ZL8weights4_0_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_0_address0;
    p_ZL8weights4_0_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_0_ce0;
    p_ZL8weights4_1_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_1_address0;
    p_ZL8weights4_1_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_1_ce0;
    p_ZL8weights4_2_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_2_address0;
    p_ZL8weights4_2_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_2_ce0;
    p_ZL8weights4_3_address0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_3_address0;
    p_ZL8weights4_3_ce0 <= grp_Matrix_Vector_Activate_Batch_7_Pipeline_VITIS_LOOP_122_1_fu_52_p_ZL8weights4_3_ce0;
    p_shl1_i_fu_89_p3 <= (p_read & ap_const_lv8_0);
    p_shl_i_fu_81_p3 <= (empty_fu_77_p1 & ap_const_lv11_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
