// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module BlackBoxJam_Matrix_Vector_Activate_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        convInp_4_dout,
        convInp_4_num_data_valid,
        convInp_4_fifo_cap,
        convInp_4_empty_n,
        convInp_4_read,
        mvOut_m_buffer_9_din,
        mvOut_m_buffer_9_num_data_valid,
        mvOut_m_buffer_9_fifo_cap,
        mvOut_m_buffer_9_full_n,
        mvOut_m_buffer_9_write,
        p_read,
        p_ZL8weights1_0_address0,
        p_ZL8weights1_0_ce0,
        p_ZL8weights1_0_q0,
        p_ZL8weights1_1_address0,
        p_ZL8weights1_1_ce0,
        p_ZL8weights1_1_q0,
        p_ZL8weights1_2_address0,
        p_ZL8weights1_2_ce0,
        p_ZL8weights1_2_q0,
        p_ZL8weights1_3_address0,
        p_ZL8weights1_3_ce0,
        p_ZL8weights1_3_q0,
        p_ZL8weights1_4_address0,
        p_ZL8weights1_4_ce0,
        p_ZL8weights1_4_q0,
        p_ZL8weights1_5_address0,
        p_ZL8weights1_5_ce0,
        p_ZL8weights1_5_q0,
        p_ZL8weights1_6_address0,
        p_ZL8weights1_6_ce0,
        p_ZL8weights1_6_q0,
        p_ZL8weights1_7_address0,
        p_ZL8weights1_7_ce0,
        p_ZL8weights1_7_q0,
        p_ZL8weights1_8_address0,
        p_ZL8weights1_8_ce0,
        p_ZL8weights1_8_q0,
        p_ZL8weights1_9_address0,
        p_ZL8weights1_9_ce0,
        p_ZL8weights1_9_q0,
        p_ZL8weights1_10_address0,
        p_ZL8weights1_10_ce0,
        p_ZL8weights1_10_q0,
        p_ZL8weights1_11_address0,
        p_ZL8weights1_11_ce0,
        p_ZL8weights1_11_q0,
        p_ZL8weights1_12_address0,
        p_ZL8weights1_12_ce0,
        p_ZL8weights1_12_q0,
        p_ZL8weights1_13_address0,
        p_ZL8weights1_13_ce0,
        p_ZL8weights1_13_q0,
        p_ZL8weights1_14_address0,
        p_ZL8weights1_14_ce0,
        p_ZL8weights1_14_q0,
        p_ZL8weights1_15_address0,
        p_ZL8weights1_15_ce0,
        p_ZL8weights1_15_q0,
        p_ZL8weights1_16_address0,
        p_ZL8weights1_16_ce0,
        p_ZL8weights1_16_q0,
        p_ZL8weights1_17_address0,
        p_ZL8weights1_17_ce0,
        p_ZL8weights1_17_q0,
        p_ZL8weights1_18_address0,
        p_ZL8weights1_18_ce0,
        p_ZL8weights1_18_q0,
        p_ZL8weights1_19_address0,
        p_ZL8weights1_19_ce0,
        p_ZL8weights1_19_q0,
        p_ZL8weights1_20_address0,
        p_ZL8weights1_20_ce0,
        p_ZL8weights1_20_q0,
        p_ZL8weights1_21_address0,
        p_ZL8weights1_21_ce0,
        p_ZL8weights1_21_q0,
        p_ZL8weights1_22_address0,
        p_ZL8weights1_22_ce0,
        p_ZL8weights1_22_q0,
        p_ZL8weights1_23_address0,
        p_ZL8weights1_23_ce0,
        p_ZL8weights1_23_q0,
        p_ZL8weights1_24_address0,
        p_ZL8weights1_24_ce0,
        p_ZL8weights1_24_q0,
        p_ZL8weights1_25_address0,
        p_ZL8weights1_25_ce0,
        p_ZL8weights1_25_q0,
        p_ZL8weights1_26_address0,
        p_ZL8weights1_26_ce0,
        p_ZL8weights1_26_q0,
        p_ZL8weights1_27_address0,
        p_ZL8weights1_27_ce0,
        p_ZL8weights1_27_q0,
        p_ZL8weights1_28_address0,
        p_ZL8weights1_28_ce0,
        p_ZL8weights1_28_q0,
        p_ZL8weights1_29_address0,
        p_ZL8weights1_29_ce0,
        p_ZL8weights1_29_q0,
        p_ZL8weights1_30_address0,
        p_ZL8weights1_30_ce0,
        p_ZL8weights1_30_q0,
        p_ZL8weights1_31_address0,
        p_ZL8weights1_31_ce0,
        p_ZL8weights1_31_q0,
        p_ZL8threshs1_0_address0,
        p_ZL8threshs1_0_ce0,
        p_ZL8threshs1_0_q0,
        p_ZL8threshs1_1_address0,
        p_ZL8threshs1_1_ce0,
        p_ZL8threshs1_1_q0,
        p_ZL8threshs1_2_address0,
        p_ZL8threshs1_2_ce0,
        p_ZL8threshs1_2_q0,
        p_ZL8threshs1_3_address0,
        p_ZL8threshs1_3_ce0,
        p_ZL8threshs1_3_q0,
        p_ZL8threshs1_4_address0,
        p_ZL8threshs1_4_ce0,
        p_ZL8threshs1_4_q0,
        p_ZL8threshs1_5_address0,
        p_ZL8threshs1_5_ce0,
        p_ZL8threshs1_5_q0,
        p_ZL8threshs1_6_address0,
        p_ZL8threshs1_6_ce0,
        p_ZL8threshs1_6_q0,
        p_ZL8threshs1_7_address0,
        p_ZL8threshs1_7_ce0,
        p_ZL8threshs1_7_q0,
        p_ZL8threshs1_8_address0,
        p_ZL8threshs1_8_ce0,
        p_ZL8threshs1_8_q0,
        p_ZL8threshs1_9_address0,
        p_ZL8threshs1_9_ce0,
        p_ZL8threshs1_9_q0,
        p_ZL8threshs1_10_address0,
        p_ZL8threshs1_10_ce0,
        p_ZL8threshs1_10_q0,
        p_ZL8threshs1_11_address0,
        p_ZL8threshs1_11_ce0,
        p_ZL8threshs1_11_q0,
        p_ZL8threshs1_12_address0,
        p_ZL8threshs1_12_ce0,
        p_ZL8threshs1_12_q0,
        p_ZL8threshs1_13_address0,
        p_ZL8threshs1_13_ce0,
        p_ZL8threshs1_13_q0,
        p_ZL8threshs1_14_address0,
        p_ZL8threshs1_14_ce0,
        p_ZL8threshs1_14_q0,
        p_ZL8threshs1_15_address0,
        p_ZL8threshs1_15_ce0,
        p_ZL8threshs1_15_q0,
        p_ZL8threshs1_16_address0,
        p_ZL8threshs1_16_ce0,
        p_ZL8threshs1_16_q0,
        p_ZL8threshs1_17_address0,
        p_ZL8threshs1_17_ce0,
        p_ZL8threshs1_17_q0,
        p_ZL8threshs1_18_address0,
        p_ZL8threshs1_18_ce0,
        p_ZL8threshs1_18_q0,
        p_ZL8threshs1_19_address0,
        p_ZL8threshs1_19_ce0,
        p_ZL8threshs1_19_q0,
        p_ZL8threshs1_20_address0,
        p_ZL8threshs1_20_ce0,
        p_ZL8threshs1_20_q0,
        p_ZL8threshs1_21_address0,
        p_ZL8threshs1_21_ce0,
        p_ZL8threshs1_21_q0,
        p_ZL8threshs1_22_address0,
        p_ZL8threshs1_22_ce0,
        p_ZL8threshs1_22_q0,
        p_ZL8threshs1_23_address0,
        p_ZL8threshs1_23_ce0,
        p_ZL8threshs1_23_q0,
        p_ZL8threshs1_24_address0,
        p_ZL8threshs1_24_ce0,
        p_ZL8threshs1_24_q0,
        p_ZL8threshs1_25_address0,
        p_ZL8threshs1_25_ce0,
        p_ZL8threshs1_25_q0,
        p_ZL8threshs1_26_address0,
        p_ZL8threshs1_26_ce0,
        p_ZL8threshs1_26_q0,
        p_ZL8threshs1_27_address0,
        p_ZL8threshs1_27_ce0,
        p_ZL8threshs1_27_q0,
        p_ZL8threshs1_28_address0,
        p_ZL8threshs1_28_ce0,
        p_ZL8threshs1_28_q0,
        p_ZL8threshs1_29_address0,
        p_ZL8threshs1_29_ce0,
        p_ZL8threshs1_29_q0,
        p_ZL8threshs1_30_address0,
        p_ZL8threshs1_30_ce0,
        p_ZL8threshs1_30_q0,
        p_ZL8threshs1_31_address0,
        p_ZL8threshs1_31_ce0,
        p_ZL8threshs1_31_q0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] convInp_4_dout;
input  [2:0] convInp_4_num_data_valid;
input  [2:0] convInp_4_fifo_cap;
input   convInp_4_empty_n;
output   convInp_4_read;
output  [31:0] mvOut_m_buffer_9_din;
input  [2:0] mvOut_m_buffer_9_num_data_valid;
input  [2:0] mvOut_m_buffer_9_fifo_cap;
input   mvOut_m_buffer_9_full_n;
output   mvOut_m_buffer_9_write;
input  [29:0] p_read;
output  [5:0] p_ZL8weights1_0_address0;
output   p_ZL8weights1_0_ce0;
input  [31:0] p_ZL8weights1_0_q0;
output  [5:0] p_ZL8weights1_1_address0;
output   p_ZL8weights1_1_ce0;
input  [31:0] p_ZL8weights1_1_q0;
output  [5:0] p_ZL8weights1_2_address0;
output   p_ZL8weights1_2_ce0;
input  [31:0] p_ZL8weights1_2_q0;
output  [5:0] p_ZL8weights1_3_address0;
output   p_ZL8weights1_3_ce0;
input  [31:0] p_ZL8weights1_3_q0;
output  [5:0] p_ZL8weights1_4_address0;
output   p_ZL8weights1_4_ce0;
input  [31:0] p_ZL8weights1_4_q0;
output  [5:0] p_ZL8weights1_5_address0;
output   p_ZL8weights1_5_ce0;
input  [31:0] p_ZL8weights1_5_q0;
output  [5:0] p_ZL8weights1_6_address0;
output   p_ZL8weights1_6_ce0;
input  [31:0] p_ZL8weights1_6_q0;
output  [5:0] p_ZL8weights1_7_address0;
output   p_ZL8weights1_7_ce0;
input  [31:0] p_ZL8weights1_7_q0;
output  [5:0] p_ZL8weights1_8_address0;
output   p_ZL8weights1_8_ce0;
input  [31:0] p_ZL8weights1_8_q0;
output  [5:0] p_ZL8weights1_9_address0;
output   p_ZL8weights1_9_ce0;
input  [31:0] p_ZL8weights1_9_q0;
output  [5:0] p_ZL8weights1_10_address0;
output   p_ZL8weights1_10_ce0;
input  [31:0] p_ZL8weights1_10_q0;
output  [5:0] p_ZL8weights1_11_address0;
output   p_ZL8weights1_11_ce0;
input  [31:0] p_ZL8weights1_11_q0;
output  [5:0] p_ZL8weights1_12_address0;
output   p_ZL8weights1_12_ce0;
input  [31:0] p_ZL8weights1_12_q0;
output  [5:0] p_ZL8weights1_13_address0;
output   p_ZL8weights1_13_ce0;
input  [31:0] p_ZL8weights1_13_q0;
output  [5:0] p_ZL8weights1_14_address0;
output   p_ZL8weights1_14_ce0;
input  [31:0] p_ZL8weights1_14_q0;
output  [5:0] p_ZL8weights1_15_address0;
output   p_ZL8weights1_15_ce0;
input  [31:0] p_ZL8weights1_15_q0;
output  [5:0] p_ZL8weights1_16_address0;
output   p_ZL8weights1_16_ce0;
input  [31:0] p_ZL8weights1_16_q0;
output  [5:0] p_ZL8weights1_17_address0;
output   p_ZL8weights1_17_ce0;
input  [31:0] p_ZL8weights1_17_q0;
output  [5:0] p_ZL8weights1_18_address0;
output   p_ZL8weights1_18_ce0;
input  [31:0] p_ZL8weights1_18_q0;
output  [5:0] p_ZL8weights1_19_address0;
output   p_ZL8weights1_19_ce0;
input  [31:0] p_ZL8weights1_19_q0;
output  [5:0] p_ZL8weights1_20_address0;
output   p_ZL8weights1_20_ce0;
input  [31:0] p_ZL8weights1_20_q0;
output  [5:0] p_ZL8weights1_21_address0;
output   p_ZL8weights1_21_ce0;
input  [31:0] p_ZL8weights1_21_q0;
output  [5:0] p_ZL8weights1_22_address0;
output   p_ZL8weights1_22_ce0;
input  [31:0] p_ZL8weights1_22_q0;
output  [5:0] p_ZL8weights1_23_address0;
output   p_ZL8weights1_23_ce0;
input  [31:0] p_ZL8weights1_23_q0;
output  [5:0] p_ZL8weights1_24_address0;
output   p_ZL8weights1_24_ce0;
input  [31:0] p_ZL8weights1_24_q0;
output  [5:0] p_ZL8weights1_25_address0;
output   p_ZL8weights1_25_ce0;
input  [31:0] p_ZL8weights1_25_q0;
output  [5:0] p_ZL8weights1_26_address0;
output   p_ZL8weights1_26_ce0;
input  [31:0] p_ZL8weights1_26_q0;
output  [5:0] p_ZL8weights1_27_address0;
output   p_ZL8weights1_27_ce0;
input  [31:0] p_ZL8weights1_27_q0;
output  [5:0] p_ZL8weights1_28_address0;
output   p_ZL8weights1_28_ce0;
input  [31:0] p_ZL8weights1_28_q0;
output  [5:0] p_ZL8weights1_29_address0;
output   p_ZL8weights1_29_ce0;
input  [31:0] p_ZL8weights1_29_q0;
output  [5:0] p_ZL8weights1_30_address0;
output   p_ZL8weights1_30_ce0;
input  [31:0] p_ZL8weights1_30_q0;
output  [5:0] p_ZL8weights1_31_address0;
output   p_ZL8weights1_31_ce0;
input  [31:0] p_ZL8weights1_31_q0;
output  [0:0] p_ZL8threshs1_0_address0;
output   p_ZL8threshs1_0_ce0;
input  [15:0] p_ZL8threshs1_0_q0;
output  [0:0] p_ZL8threshs1_1_address0;
output   p_ZL8threshs1_1_ce0;
input  [15:0] p_ZL8threshs1_1_q0;
output  [0:0] p_ZL8threshs1_2_address0;
output   p_ZL8threshs1_2_ce0;
input  [15:0] p_ZL8threshs1_2_q0;
output  [0:0] p_ZL8threshs1_3_address0;
output   p_ZL8threshs1_3_ce0;
input  [15:0] p_ZL8threshs1_3_q0;
output  [0:0] p_ZL8threshs1_4_address0;
output   p_ZL8threshs1_4_ce0;
input  [15:0] p_ZL8threshs1_4_q0;
output  [0:0] p_ZL8threshs1_5_address0;
output   p_ZL8threshs1_5_ce0;
input  [15:0] p_ZL8threshs1_5_q0;
output  [0:0] p_ZL8threshs1_6_address0;
output   p_ZL8threshs1_6_ce0;
input  [15:0] p_ZL8threshs1_6_q0;
output  [0:0] p_ZL8threshs1_7_address0;
output   p_ZL8threshs1_7_ce0;
input  [15:0] p_ZL8threshs1_7_q0;
output  [0:0] p_ZL8threshs1_8_address0;
output   p_ZL8threshs1_8_ce0;
input  [15:0] p_ZL8threshs1_8_q0;
output  [0:0] p_ZL8threshs1_9_address0;
output   p_ZL8threshs1_9_ce0;
input  [15:0] p_ZL8threshs1_9_q0;
output  [0:0] p_ZL8threshs1_10_address0;
output   p_ZL8threshs1_10_ce0;
input  [15:0] p_ZL8threshs1_10_q0;
output  [0:0] p_ZL8threshs1_11_address0;
output   p_ZL8threshs1_11_ce0;
input  [15:0] p_ZL8threshs1_11_q0;
output  [0:0] p_ZL8threshs1_12_address0;
output   p_ZL8threshs1_12_ce0;
input  [15:0] p_ZL8threshs1_12_q0;
output  [0:0] p_ZL8threshs1_13_address0;
output   p_ZL8threshs1_13_ce0;
input  [15:0] p_ZL8threshs1_13_q0;
output  [0:0] p_ZL8threshs1_14_address0;
output   p_ZL8threshs1_14_ce0;
input  [15:0] p_ZL8threshs1_14_q0;
output  [0:0] p_ZL8threshs1_15_address0;
output   p_ZL8threshs1_15_ce0;
input  [15:0] p_ZL8threshs1_15_q0;
output  [0:0] p_ZL8threshs1_16_address0;
output   p_ZL8threshs1_16_ce0;
input  [15:0] p_ZL8threshs1_16_q0;
output  [0:0] p_ZL8threshs1_17_address0;
output   p_ZL8threshs1_17_ce0;
input  [15:0] p_ZL8threshs1_17_q0;
output  [0:0] p_ZL8threshs1_18_address0;
output   p_ZL8threshs1_18_ce0;
input  [15:0] p_ZL8threshs1_18_q0;
output  [0:0] p_ZL8threshs1_19_address0;
output   p_ZL8threshs1_19_ce0;
input  [15:0] p_ZL8threshs1_19_q0;
output  [0:0] p_ZL8threshs1_20_address0;
output   p_ZL8threshs1_20_ce0;
input  [15:0] p_ZL8threshs1_20_q0;
output  [0:0] p_ZL8threshs1_21_address0;
output   p_ZL8threshs1_21_ce0;
input  [15:0] p_ZL8threshs1_21_q0;
output  [0:0] p_ZL8threshs1_22_address0;
output   p_ZL8threshs1_22_ce0;
input  [15:0] p_ZL8threshs1_22_q0;
output  [0:0] p_ZL8threshs1_23_address0;
output   p_ZL8threshs1_23_ce0;
input  [15:0] p_ZL8threshs1_23_q0;
output  [0:0] p_ZL8threshs1_24_address0;
output   p_ZL8threshs1_24_ce0;
input  [15:0] p_ZL8threshs1_24_q0;
output  [0:0] p_ZL8threshs1_25_address0;
output   p_ZL8threshs1_25_ce0;
input  [15:0] p_ZL8threshs1_25_q0;
output  [0:0] p_ZL8threshs1_26_address0;
output   p_ZL8threshs1_26_ce0;
input  [15:0] p_ZL8threshs1_26_q0;
output  [0:0] p_ZL8threshs1_27_address0;
output   p_ZL8threshs1_27_ce0;
input  [15:0] p_ZL8threshs1_27_q0;
output  [0:0] p_ZL8threshs1_28_address0;
output   p_ZL8threshs1_28_ce0;
input  [15:0] p_ZL8threshs1_28_q0;
output  [0:0] p_ZL8threshs1_29_address0;
output   p_ZL8threshs1_29_ce0;
input  [15:0] p_ZL8threshs1_29_q0;
output  [0:0] p_ZL8threshs1_30_address0;
output   p_ZL8threshs1_30_ce0;
input  [15:0] p_ZL8threshs1_30_q0;
output  [0:0] p_ZL8threshs1_31_address0;
output   p_ZL8threshs1_31_ce0;
input  [15:0] p_ZL8threshs1_31_q0;

reg ap_done;
reg ap_idle;
reg start_write;
reg convInp_4_read;
reg mvOut_m_buffer_9_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [31:0] mul_i_fu_321_p2;
reg   [31:0] mul_i_reg_327;
reg    ap_block_state1;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_idle;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_ready;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_convInp_4_read;
wire   [31:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_mvOut_m_buffer_9_din;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_mvOut_m_buffer_9_write;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_0_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_0_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_1_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_1_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_2_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_2_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_3_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_3_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_4_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_4_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_5_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_5_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_6_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_6_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_7_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_7_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_8_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_8_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_9_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_9_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_10_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_10_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_11_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_11_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_12_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_12_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_13_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_13_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_14_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_14_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_15_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_15_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_16_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_16_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_17_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_17_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_18_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_18_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_19_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_19_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_20_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_20_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_21_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_21_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_22_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_22_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_23_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_23_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_24_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_24_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_25_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_25_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_26_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_26_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_27_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_27_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_28_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_28_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_29_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_29_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_30_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_30_ce0;
wire   [5:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_31_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_31_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_0_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_0_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_1_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_1_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_2_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_2_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_3_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_3_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_4_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_4_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_5_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_5_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_6_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_6_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_7_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_7_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_8_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_8_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_9_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_9_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_10_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_10_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_11_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_11_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_12_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_12_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_13_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_13_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_14_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_14_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_15_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_15_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_16_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_16_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_17_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_17_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_18_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_18_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_19_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_19_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_20_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_20_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_21_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_21_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_22_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_22_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_23_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_23_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_24_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_24_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_25_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_25_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_26_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_26_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_27_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_27_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_28_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_28_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_29_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_29_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_30_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_30_ce0;
wire   [0:0] grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_31_address0;
wire    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_31_ce0;
reg    grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [26:0] empty_fu_301_p1;
wire   [31:0] p_shl_i_fu_305_p3;
wire   [31:0] p_shl1_i_fu_313_p3;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start_reg = 1'b0;
end

BlackBoxJam_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1 grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start),
    .ap_done(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done),
    .ap_idle(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_idle),
    .ap_ready(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_ready),
    .convInp_4_dout(convInp_4_dout),
    .convInp_4_num_data_valid(3'd0),
    .convInp_4_fifo_cap(3'd0),
    .convInp_4_empty_n(convInp_4_empty_n),
    .convInp_4_read(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_convInp_4_read),
    .mvOut_m_buffer_9_din(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_mvOut_m_buffer_9_din),
    .mvOut_m_buffer_9_num_data_valid(3'd0),
    .mvOut_m_buffer_9_fifo_cap(3'd0),
    .mvOut_m_buffer_9_full_n(mvOut_m_buffer_9_full_n),
    .mvOut_m_buffer_9_write(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_mvOut_m_buffer_9_write),
    .mul_i(mul_i_reg_327),
    .p_ZL8weights1_0_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_0_address0),
    .p_ZL8weights1_0_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_0_ce0),
    .p_ZL8weights1_0_q0(p_ZL8weights1_0_q0),
    .p_ZL8weights1_1_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_1_address0),
    .p_ZL8weights1_1_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_1_ce0),
    .p_ZL8weights1_1_q0(p_ZL8weights1_1_q0),
    .p_ZL8weights1_2_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_2_address0),
    .p_ZL8weights1_2_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_2_ce0),
    .p_ZL8weights1_2_q0(p_ZL8weights1_2_q0),
    .p_ZL8weights1_3_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_3_address0),
    .p_ZL8weights1_3_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_3_ce0),
    .p_ZL8weights1_3_q0(p_ZL8weights1_3_q0),
    .p_ZL8weights1_4_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_4_address0),
    .p_ZL8weights1_4_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_4_ce0),
    .p_ZL8weights1_4_q0(p_ZL8weights1_4_q0),
    .p_ZL8weights1_5_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_5_address0),
    .p_ZL8weights1_5_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_5_ce0),
    .p_ZL8weights1_5_q0(p_ZL8weights1_5_q0),
    .p_ZL8weights1_6_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_6_address0),
    .p_ZL8weights1_6_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_6_ce0),
    .p_ZL8weights1_6_q0(p_ZL8weights1_6_q0),
    .p_ZL8weights1_7_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_7_address0),
    .p_ZL8weights1_7_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_7_ce0),
    .p_ZL8weights1_7_q0(p_ZL8weights1_7_q0),
    .p_ZL8weights1_8_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_8_address0),
    .p_ZL8weights1_8_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_8_ce0),
    .p_ZL8weights1_8_q0(p_ZL8weights1_8_q0),
    .p_ZL8weights1_9_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_9_address0),
    .p_ZL8weights1_9_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_9_ce0),
    .p_ZL8weights1_9_q0(p_ZL8weights1_9_q0),
    .p_ZL8weights1_10_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_10_address0),
    .p_ZL8weights1_10_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_10_ce0),
    .p_ZL8weights1_10_q0(p_ZL8weights1_10_q0),
    .p_ZL8weights1_11_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_11_address0),
    .p_ZL8weights1_11_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_11_ce0),
    .p_ZL8weights1_11_q0(p_ZL8weights1_11_q0),
    .p_ZL8weights1_12_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_12_address0),
    .p_ZL8weights1_12_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_12_ce0),
    .p_ZL8weights1_12_q0(p_ZL8weights1_12_q0),
    .p_ZL8weights1_13_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_13_address0),
    .p_ZL8weights1_13_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_13_ce0),
    .p_ZL8weights1_13_q0(p_ZL8weights1_13_q0),
    .p_ZL8weights1_14_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_14_address0),
    .p_ZL8weights1_14_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_14_ce0),
    .p_ZL8weights1_14_q0(p_ZL8weights1_14_q0),
    .p_ZL8weights1_15_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_15_address0),
    .p_ZL8weights1_15_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_15_ce0),
    .p_ZL8weights1_15_q0(p_ZL8weights1_15_q0),
    .p_ZL8weights1_16_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_16_address0),
    .p_ZL8weights1_16_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_16_ce0),
    .p_ZL8weights1_16_q0(p_ZL8weights1_16_q0),
    .p_ZL8weights1_17_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_17_address0),
    .p_ZL8weights1_17_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_17_ce0),
    .p_ZL8weights1_17_q0(p_ZL8weights1_17_q0),
    .p_ZL8weights1_18_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_18_address0),
    .p_ZL8weights1_18_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_18_ce0),
    .p_ZL8weights1_18_q0(p_ZL8weights1_18_q0),
    .p_ZL8weights1_19_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_19_address0),
    .p_ZL8weights1_19_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_19_ce0),
    .p_ZL8weights1_19_q0(p_ZL8weights1_19_q0),
    .p_ZL8weights1_20_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_20_address0),
    .p_ZL8weights1_20_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_20_ce0),
    .p_ZL8weights1_20_q0(p_ZL8weights1_20_q0),
    .p_ZL8weights1_21_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_21_address0),
    .p_ZL8weights1_21_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_21_ce0),
    .p_ZL8weights1_21_q0(p_ZL8weights1_21_q0),
    .p_ZL8weights1_22_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_22_address0),
    .p_ZL8weights1_22_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_22_ce0),
    .p_ZL8weights1_22_q0(p_ZL8weights1_22_q0),
    .p_ZL8weights1_23_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_23_address0),
    .p_ZL8weights1_23_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_23_ce0),
    .p_ZL8weights1_23_q0(p_ZL8weights1_23_q0),
    .p_ZL8weights1_24_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_24_address0),
    .p_ZL8weights1_24_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_24_ce0),
    .p_ZL8weights1_24_q0(p_ZL8weights1_24_q0),
    .p_ZL8weights1_25_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_25_address0),
    .p_ZL8weights1_25_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_25_ce0),
    .p_ZL8weights1_25_q0(p_ZL8weights1_25_q0),
    .p_ZL8weights1_26_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_26_address0),
    .p_ZL8weights1_26_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_26_ce0),
    .p_ZL8weights1_26_q0(p_ZL8weights1_26_q0),
    .p_ZL8weights1_27_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_27_address0),
    .p_ZL8weights1_27_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_27_ce0),
    .p_ZL8weights1_27_q0(p_ZL8weights1_27_q0),
    .p_ZL8weights1_28_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_28_address0),
    .p_ZL8weights1_28_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_28_ce0),
    .p_ZL8weights1_28_q0(p_ZL8weights1_28_q0),
    .p_ZL8weights1_29_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_29_address0),
    .p_ZL8weights1_29_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_29_ce0),
    .p_ZL8weights1_29_q0(p_ZL8weights1_29_q0),
    .p_ZL8weights1_30_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_30_address0),
    .p_ZL8weights1_30_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_30_ce0),
    .p_ZL8weights1_30_q0(p_ZL8weights1_30_q0),
    .p_ZL8weights1_31_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_31_address0),
    .p_ZL8weights1_31_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_31_ce0),
    .p_ZL8weights1_31_q0(p_ZL8weights1_31_q0),
    .p_ZL8threshs1_0_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_0_address0),
    .p_ZL8threshs1_0_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_0_ce0),
    .p_ZL8threshs1_0_q0(p_ZL8threshs1_0_q0),
    .p_ZL8threshs1_1_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_1_address0),
    .p_ZL8threshs1_1_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_1_ce0),
    .p_ZL8threshs1_1_q0(p_ZL8threshs1_1_q0),
    .p_ZL8threshs1_2_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_2_address0),
    .p_ZL8threshs1_2_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_2_ce0),
    .p_ZL8threshs1_2_q0(p_ZL8threshs1_2_q0),
    .p_ZL8threshs1_3_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_3_address0),
    .p_ZL8threshs1_3_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_3_ce0),
    .p_ZL8threshs1_3_q0(p_ZL8threshs1_3_q0),
    .p_ZL8threshs1_4_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_4_address0),
    .p_ZL8threshs1_4_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_4_ce0),
    .p_ZL8threshs1_4_q0(p_ZL8threshs1_4_q0),
    .p_ZL8threshs1_5_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_5_address0),
    .p_ZL8threshs1_5_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_5_ce0),
    .p_ZL8threshs1_5_q0(p_ZL8threshs1_5_q0),
    .p_ZL8threshs1_6_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_6_address0),
    .p_ZL8threshs1_6_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_6_ce0),
    .p_ZL8threshs1_6_q0(p_ZL8threshs1_6_q0),
    .p_ZL8threshs1_7_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_7_address0),
    .p_ZL8threshs1_7_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_7_ce0),
    .p_ZL8threshs1_7_q0(p_ZL8threshs1_7_q0),
    .p_ZL8threshs1_8_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_8_address0),
    .p_ZL8threshs1_8_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_8_ce0),
    .p_ZL8threshs1_8_q0(p_ZL8threshs1_8_q0),
    .p_ZL8threshs1_9_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_9_address0),
    .p_ZL8threshs1_9_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_9_ce0),
    .p_ZL8threshs1_9_q0(p_ZL8threshs1_9_q0),
    .p_ZL8threshs1_10_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_10_address0),
    .p_ZL8threshs1_10_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_10_ce0),
    .p_ZL8threshs1_10_q0(p_ZL8threshs1_10_q0),
    .p_ZL8threshs1_11_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_11_address0),
    .p_ZL8threshs1_11_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_11_ce0),
    .p_ZL8threshs1_11_q0(p_ZL8threshs1_11_q0),
    .p_ZL8threshs1_12_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_12_address0),
    .p_ZL8threshs1_12_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_12_ce0),
    .p_ZL8threshs1_12_q0(p_ZL8threshs1_12_q0),
    .p_ZL8threshs1_13_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_13_address0),
    .p_ZL8threshs1_13_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_13_ce0),
    .p_ZL8threshs1_13_q0(p_ZL8threshs1_13_q0),
    .p_ZL8threshs1_14_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_14_address0),
    .p_ZL8threshs1_14_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_14_ce0),
    .p_ZL8threshs1_14_q0(p_ZL8threshs1_14_q0),
    .p_ZL8threshs1_15_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_15_address0),
    .p_ZL8threshs1_15_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_15_ce0),
    .p_ZL8threshs1_15_q0(p_ZL8threshs1_15_q0),
    .p_ZL8threshs1_16_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_16_address0),
    .p_ZL8threshs1_16_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_16_ce0),
    .p_ZL8threshs1_16_q0(p_ZL8threshs1_16_q0),
    .p_ZL8threshs1_17_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_17_address0),
    .p_ZL8threshs1_17_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_17_ce0),
    .p_ZL8threshs1_17_q0(p_ZL8threshs1_17_q0),
    .p_ZL8threshs1_18_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_18_address0),
    .p_ZL8threshs1_18_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_18_ce0),
    .p_ZL8threshs1_18_q0(p_ZL8threshs1_18_q0),
    .p_ZL8threshs1_19_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_19_address0),
    .p_ZL8threshs1_19_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_19_ce0),
    .p_ZL8threshs1_19_q0(p_ZL8threshs1_19_q0),
    .p_ZL8threshs1_20_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_20_address0),
    .p_ZL8threshs1_20_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_20_ce0),
    .p_ZL8threshs1_20_q0(p_ZL8threshs1_20_q0),
    .p_ZL8threshs1_21_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_21_address0),
    .p_ZL8threshs1_21_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_21_ce0),
    .p_ZL8threshs1_21_q0(p_ZL8threshs1_21_q0),
    .p_ZL8threshs1_22_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_22_address0),
    .p_ZL8threshs1_22_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_22_ce0),
    .p_ZL8threshs1_22_q0(p_ZL8threshs1_22_q0),
    .p_ZL8threshs1_23_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_23_address0),
    .p_ZL8threshs1_23_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_23_ce0),
    .p_ZL8threshs1_23_q0(p_ZL8threshs1_23_q0),
    .p_ZL8threshs1_24_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_24_address0),
    .p_ZL8threshs1_24_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_24_ce0),
    .p_ZL8threshs1_24_q0(p_ZL8threshs1_24_q0),
    .p_ZL8threshs1_25_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_25_address0),
    .p_ZL8threshs1_25_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_25_ce0),
    .p_ZL8threshs1_25_q0(p_ZL8threshs1_25_q0),
    .p_ZL8threshs1_26_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_26_address0),
    .p_ZL8threshs1_26_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_26_ce0),
    .p_ZL8threshs1_26_q0(p_ZL8threshs1_26_q0),
    .p_ZL8threshs1_27_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_27_address0),
    .p_ZL8threshs1_27_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_27_ce0),
    .p_ZL8threshs1_27_q0(p_ZL8threshs1_27_q0),
    .p_ZL8threshs1_28_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_28_address0),
    .p_ZL8threshs1_28_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_28_ce0),
    .p_ZL8threshs1_28_q0(p_ZL8threshs1_28_q0),
    .p_ZL8threshs1_29_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_29_address0),
    .p_ZL8threshs1_29_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_29_ce0),
    .p_ZL8threshs1_29_q0(p_ZL8threshs1_29_q0),
    .p_ZL8threshs1_30_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_30_address0),
    .p_ZL8threshs1_30_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_30_ce0),
    .p_ZL8threshs1_30_q0(p_ZL8threshs1_30_q0),
    .p_ZL8threshs1_31_address0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_31_address0),
    .p_ZL8threshs1_31_ce0(grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_31_ce0),
    .p_ZL8threshs1_31_q0(p_ZL8threshs1_31_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_ready == 1'b1)) begin
            grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_i_reg_327[31 : 2] <= mul_i_fu_321_p2[31 : 2];
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        convInp_4_read = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_convInp_4_read;
    end else begin
        convInp_4_read = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mvOut_m_buffer_9_write = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_mvOut_m_buffer_9_write;
    end else begin
        mvOut_m_buffer_9_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign empty_fu_301_p1 = p_read[26:0];

assign grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_ap_start_reg;

assign mul_i_fu_321_p2 = (p_shl_i_fu_305_p3 + p_shl1_i_fu_313_p3);

assign mvOut_m_buffer_9_din = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_mvOut_m_buffer_9_din;

assign p_ZL8threshs1_0_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_0_address0;

assign p_ZL8threshs1_0_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_0_ce0;

assign p_ZL8threshs1_10_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_10_address0;

assign p_ZL8threshs1_10_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_10_ce0;

assign p_ZL8threshs1_11_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_11_address0;

assign p_ZL8threshs1_11_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_11_ce0;

assign p_ZL8threshs1_12_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_12_address0;

assign p_ZL8threshs1_12_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_12_ce0;

assign p_ZL8threshs1_13_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_13_address0;

assign p_ZL8threshs1_13_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_13_ce0;

assign p_ZL8threshs1_14_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_14_address0;

assign p_ZL8threshs1_14_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_14_ce0;

assign p_ZL8threshs1_15_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_15_address0;

assign p_ZL8threshs1_15_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_15_ce0;

assign p_ZL8threshs1_16_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_16_address0;

assign p_ZL8threshs1_16_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_16_ce0;

assign p_ZL8threshs1_17_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_17_address0;

assign p_ZL8threshs1_17_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_17_ce0;

assign p_ZL8threshs1_18_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_18_address0;

assign p_ZL8threshs1_18_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_18_ce0;

assign p_ZL8threshs1_19_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_19_address0;

assign p_ZL8threshs1_19_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_19_ce0;

assign p_ZL8threshs1_1_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_1_address0;

assign p_ZL8threshs1_1_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_1_ce0;

assign p_ZL8threshs1_20_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_20_address0;

assign p_ZL8threshs1_20_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_20_ce0;

assign p_ZL8threshs1_21_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_21_address0;

assign p_ZL8threshs1_21_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_21_ce0;

assign p_ZL8threshs1_22_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_22_address0;

assign p_ZL8threshs1_22_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_22_ce0;

assign p_ZL8threshs1_23_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_23_address0;

assign p_ZL8threshs1_23_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_23_ce0;

assign p_ZL8threshs1_24_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_24_address0;

assign p_ZL8threshs1_24_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_24_ce0;

assign p_ZL8threshs1_25_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_25_address0;

assign p_ZL8threshs1_25_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_25_ce0;

assign p_ZL8threshs1_26_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_26_address0;

assign p_ZL8threshs1_26_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_26_ce0;

assign p_ZL8threshs1_27_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_27_address0;

assign p_ZL8threshs1_27_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_27_ce0;

assign p_ZL8threshs1_28_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_28_address0;

assign p_ZL8threshs1_28_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_28_ce0;

assign p_ZL8threshs1_29_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_29_address0;

assign p_ZL8threshs1_29_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_29_ce0;

assign p_ZL8threshs1_2_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_2_address0;

assign p_ZL8threshs1_2_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_2_ce0;

assign p_ZL8threshs1_30_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_30_address0;

assign p_ZL8threshs1_30_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_30_ce0;

assign p_ZL8threshs1_31_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_31_address0;

assign p_ZL8threshs1_31_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_31_ce0;

assign p_ZL8threshs1_3_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_3_address0;

assign p_ZL8threshs1_3_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_3_ce0;

assign p_ZL8threshs1_4_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_4_address0;

assign p_ZL8threshs1_4_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_4_ce0;

assign p_ZL8threshs1_5_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_5_address0;

assign p_ZL8threshs1_5_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_5_ce0;

assign p_ZL8threshs1_6_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_6_address0;

assign p_ZL8threshs1_6_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_6_ce0;

assign p_ZL8threshs1_7_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_7_address0;

assign p_ZL8threshs1_7_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_7_ce0;

assign p_ZL8threshs1_8_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_8_address0;

assign p_ZL8threshs1_8_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_8_ce0;

assign p_ZL8threshs1_9_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_9_address0;

assign p_ZL8threshs1_9_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8threshs1_9_ce0;

assign p_ZL8weights1_0_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_0_address0;

assign p_ZL8weights1_0_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_0_ce0;

assign p_ZL8weights1_10_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_10_address0;

assign p_ZL8weights1_10_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_10_ce0;

assign p_ZL8weights1_11_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_11_address0;

assign p_ZL8weights1_11_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_11_ce0;

assign p_ZL8weights1_12_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_12_address0;

assign p_ZL8weights1_12_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_12_ce0;

assign p_ZL8weights1_13_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_13_address0;

assign p_ZL8weights1_13_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_13_ce0;

assign p_ZL8weights1_14_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_14_address0;

assign p_ZL8weights1_14_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_14_ce0;

assign p_ZL8weights1_15_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_15_address0;

assign p_ZL8weights1_15_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_15_ce0;

assign p_ZL8weights1_16_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_16_address0;

assign p_ZL8weights1_16_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_16_ce0;

assign p_ZL8weights1_17_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_17_address0;

assign p_ZL8weights1_17_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_17_ce0;

assign p_ZL8weights1_18_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_18_address0;

assign p_ZL8weights1_18_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_18_ce0;

assign p_ZL8weights1_19_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_19_address0;

assign p_ZL8weights1_19_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_19_ce0;

assign p_ZL8weights1_1_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_1_address0;

assign p_ZL8weights1_1_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_1_ce0;

assign p_ZL8weights1_20_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_20_address0;

assign p_ZL8weights1_20_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_20_ce0;

assign p_ZL8weights1_21_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_21_address0;

assign p_ZL8weights1_21_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_21_ce0;

assign p_ZL8weights1_22_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_22_address0;

assign p_ZL8weights1_22_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_22_ce0;

assign p_ZL8weights1_23_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_23_address0;

assign p_ZL8weights1_23_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_23_ce0;

assign p_ZL8weights1_24_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_24_address0;

assign p_ZL8weights1_24_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_24_ce0;

assign p_ZL8weights1_25_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_25_address0;

assign p_ZL8weights1_25_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_25_ce0;

assign p_ZL8weights1_26_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_26_address0;

assign p_ZL8weights1_26_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_26_ce0;

assign p_ZL8weights1_27_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_27_address0;

assign p_ZL8weights1_27_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_27_ce0;

assign p_ZL8weights1_28_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_28_address0;

assign p_ZL8weights1_28_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_28_ce0;

assign p_ZL8weights1_29_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_29_address0;

assign p_ZL8weights1_29_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_29_ce0;

assign p_ZL8weights1_2_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_2_address0;

assign p_ZL8weights1_2_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_2_ce0;

assign p_ZL8weights1_30_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_30_address0;

assign p_ZL8weights1_30_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_30_ce0;

assign p_ZL8weights1_31_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_31_address0;

assign p_ZL8weights1_31_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_31_ce0;

assign p_ZL8weights1_3_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_3_address0;

assign p_ZL8weights1_3_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_3_ce0;

assign p_ZL8weights1_4_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_4_address0;

assign p_ZL8weights1_4_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_4_ce0;

assign p_ZL8weights1_5_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_5_address0;

assign p_ZL8weights1_5_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_5_ce0;

assign p_ZL8weights1_6_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_6_address0;

assign p_ZL8weights1_6_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_6_ce0;

assign p_ZL8weights1_7_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_7_address0;

assign p_ZL8weights1_7_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_7_ce0;

assign p_ZL8weights1_8_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_8_address0;

assign p_ZL8weights1_8_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_8_ce0;

assign p_ZL8weights1_9_address0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_9_address0;

assign p_ZL8weights1_9_ce0 = grp_Matrix_Vector_Activate_Batch_Pipeline_VITIS_LOOP_122_1_fu_164_p_ZL8weights1_9_ce0;

assign p_shl1_i_fu_313_p3 = {{p_read}, {2'd0}};

assign p_shl_i_fu_305_p3 = {{empty_fu_301_p1}, {5'd0}};

assign start_out = real_start;

always @ (posedge ap_clk) begin
    mul_i_reg_327[1:0] <= 2'b00;
end

endmodule //BlackBoxJam_Matrix_Vector_Activate_Batch
