// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module BlackBoxJam_Stream2Mem_Batch_64u_128u_Pipeline_VITIS_LOOP_153_15 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        memOutStrm34_dout,
        memOutStrm34_num_data_valid,
        memOutStrm34_fifo_cap,
        memOutStrm34_empty_n,
        memOutStrm34_read,
        m_axi_hostmem_AWVALID,
        m_axi_hostmem_AWREADY,
        m_axi_hostmem_AWADDR,
        m_axi_hostmem_AWID,
        m_axi_hostmem_AWLEN,
        m_axi_hostmem_AWSIZE,
        m_axi_hostmem_AWBURST,
        m_axi_hostmem_AWLOCK,
        m_axi_hostmem_AWCACHE,
        m_axi_hostmem_AWPROT,
        m_axi_hostmem_AWQOS,
        m_axi_hostmem_AWREGION,
        m_axi_hostmem_AWUSER,
        m_axi_hostmem_WVALID,
        m_axi_hostmem_WREADY,
        m_axi_hostmem_WDATA,
        m_axi_hostmem_WSTRB,
        m_axi_hostmem_WLAST,
        m_axi_hostmem_WID,
        m_axi_hostmem_WUSER,
        m_axi_hostmem_ARVALID,
        m_axi_hostmem_ARREADY,
        m_axi_hostmem_ARADDR,
        m_axi_hostmem_ARID,
        m_axi_hostmem_ARLEN,
        m_axi_hostmem_ARSIZE,
        m_axi_hostmem_ARBURST,
        m_axi_hostmem_ARLOCK,
        m_axi_hostmem_ARCACHE,
        m_axi_hostmem_ARPROT,
        m_axi_hostmem_ARQOS,
        m_axi_hostmem_ARREGION,
        m_axi_hostmem_ARUSER,
        m_axi_hostmem_RVALID,
        m_axi_hostmem_RREADY,
        m_axi_hostmem_RDATA,
        m_axi_hostmem_RLAST,
        m_axi_hostmem_RID,
        m_axi_hostmem_RFIFONUM,
        m_axi_hostmem_RUSER,
        m_axi_hostmem_RRESP,
        m_axi_hostmem_BVALID,
        m_axi_hostmem_BREADY,
        m_axi_hostmem_BRESP,
        m_axi_hostmem_BID,
        m_axi_hostmem_BUSER,
        sext_ln153
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] memOutStrm34_dout;
input  [2:0] memOutStrm34_num_data_valid;
input  [2:0] memOutStrm34_fifo_cap;
input   memOutStrm34_empty_n;
output   memOutStrm34_read;
output   m_axi_hostmem_AWVALID;
input   m_axi_hostmem_AWREADY;
output  [63:0] m_axi_hostmem_AWADDR;
output  [0:0] m_axi_hostmem_AWID;
output  [31:0] m_axi_hostmem_AWLEN;
output  [2:0] m_axi_hostmem_AWSIZE;
output  [1:0] m_axi_hostmem_AWBURST;
output  [1:0] m_axi_hostmem_AWLOCK;
output  [3:0] m_axi_hostmem_AWCACHE;
output  [2:0] m_axi_hostmem_AWPROT;
output  [3:0] m_axi_hostmem_AWQOS;
output  [3:0] m_axi_hostmem_AWREGION;
output  [0:0] m_axi_hostmem_AWUSER;
output   m_axi_hostmem_WVALID;
input   m_axi_hostmem_WREADY;
output  [63:0] m_axi_hostmem_WDATA;
output  [7:0] m_axi_hostmem_WSTRB;
output   m_axi_hostmem_WLAST;
output  [0:0] m_axi_hostmem_WID;
output  [0:0] m_axi_hostmem_WUSER;
output   m_axi_hostmem_ARVALID;
input   m_axi_hostmem_ARREADY;
output  [63:0] m_axi_hostmem_ARADDR;
output  [0:0] m_axi_hostmem_ARID;
output  [31:0] m_axi_hostmem_ARLEN;
output  [2:0] m_axi_hostmem_ARSIZE;
output  [1:0] m_axi_hostmem_ARBURST;
output  [1:0] m_axi_hostmem_ARLOCK;
output  [3:0] m_axi_hostmem_ARCACHE;
output  [2:0] m_axi_hostmem_ARPROT;
output  [3:0] m_axi_hostmem_ARQOS;
output  [3:0] m_axi_hostmem_ARREGION;
output  [0:0] m_axi_hostmem_ARUSER;
input   m_axi_hostmem_RVALID;
output   m_axi_hostmem_RREADY;
input  [63:0] m_axi_hostmem_RDATA;
input   m_axi_hostmem_RLAST;
input  [0:0] m_axi_hostmem_RID;
input  [8:0] m_axi_hostmem_RFIFONUM;
input  [0:0] m_axi_hostmem_RUSER;
input  [1:0] m_axi_hostmem_RRESP;
input   m_axi_hostmem_BVALID;
output   m_axi_hostmem_BREADY;
input  [1:0] m_axi_hostmem_BRESP;
input  [0:0] m_axi_hostmem_BID;
input  [0:0] m_axi_hostmem_BUSER;
input  [60:0] sext_ln153;

reg ap_idle;
reg memOutStrm34_read;
reg m_axi_hostmem_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln153_fu_88_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    hostmem_blk_n_W;
wire    ap_block_pp0_stage0;
reg    memOutStrm34_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] e_reg_127;
reg    ap_block_pp0_stage0_01001;
reg   [4:0] i_fu_52;
wire   [4:0] add_ln153_fu_94_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_52 = 5'd0;
#0 ap_done_reg = 1'b0;
end

BlackBoxJam_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln153_fu_88_p2 == 1'd0))) begin
            i_fu_52 <= add_ln153_fu_94_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_52 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        e_reg_127 <= memOutStrm34_dout;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln153_fu_88_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_52;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        hostmem_blk_n_W = m_axi_hostmem_WREADY;
    end else begin
        hostmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_hostmem_WVALID = 1'b1;
    end else begin
        m_axi_hostmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        memOutStrm34_blk_n = memOutStrm34_empty_n;
    end else begin
        memOutStrm34_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        memOutStrm34_read = 1'b1;
    end else begin
        memOutStrm34_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln153_fu_94_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_hostmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_hostmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (memOutStrm34_empty_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln153_fu_88_p2 = ((ap_sig_allocacmp_i_2 == 5'd16) ? 1'b1 : 1'b0);

assign m_axi_hostmem_ARADDR = 64'd0;

assign m_axi_hostmem_ARBURST = 2'd0;

assign m_axi_hostmem_ARCACHE = 4'd0;

assign m_axi_hostmem_ARID = 1'd0;

assign m_axi_hostmem_ARLEN = 32'd0;

assign m_axi_hostmem_ARLOCK = 2'd0;

assign m_axi_hostmem_ARPROT = 3'd0;

assign m_axi_hostmem_ARQOS = 4'd0;

assign m_axi_hostmem_ARREGION = 4'd0;

assign m_axi_hostmem_ARSIZE = 3'd0;

assign m_axi_hostmem_ARUSER = 1'd0;

assign m_axi_hostmem_ARVALID = 1'b0;

assign m_axi_hostmem_AWADDR = 64'd0;

assign m_axi_hostmem_AWBURST = 2'd0;

assign m_axi_hostmem_AWCACHE = 4'd0;

assign m_axi_hostmem_AWID = 1'd0;

assign m_axi_hostmem_AWLEN = 32'd0;

assign m_axi_hostmem_AWLOCK = 2'd0;

assign m_axi_hostmem_AWPROT = 3'd0;

assign m_axi_hostmem_AWQOS = 4'd0;

assign m_axi_hostmem_AWREGION = 4'd0;

assign m_axi_hostmem_AWSIZE = 3'd0;

assign m_axi_hostmem_AWUSER = 1'd0;

assign m_axi_hostmem_AWVALID = 1'b0;

assign m_axi_hostmem_BREADY = 1'b0;

assign m_axi_hostmem_RREADY = 1'b0;

assign m_axi_hostmem_WDATA = e_reg_127;

assign m_axi_hostmem_WID = 1'd0;

assign m_axi_hostmem_WLAST = 1'b0;

assign m_axi_hostmem_WSTRB = 8'd255;

assign m_axi_hostmem_WUSER = 1'd0;

endmodule //BlackBoxJam_Stream2Mem_Batch_64u_128u_Pipeline_VITIS_LOOP_153_15
